# Generated by Django 4.2.10 on 2024-03-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_workspaceconfig"),
        ("orgs", "0016_organization_metafields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="config",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org",
                to="user.workspaceconfig",
            ),
        ),
    ]
