# Generated by Django 3.2 on 2021-04-27 13:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20210426_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customs',
            name='duty',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
