# Generated by Django 3.2.12 on 2022-03-24 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_shipment_invoice'),
        ('orders', '0009_auto_20220321_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_order', to='manager.address'),
        ),
    ]
