# Generated by Django 3.2.13 on 2022-07-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_alter_tracking_shipment'),
        ('orders', '0010_auto_20220324_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_to_order', to='manager.address'),
        ),
    ]
