from enum import Enum, auto


class FedexUnit:
    
    class ServiceType(Enum):
        EUROPE_FIRST_INTERNATIONAL_PRIORITY                   =    "EUROPE_FIRST_INTERNATIONAL_PRIORITY"
        FEDEX_1_DAY_FREIGHT                                   =    "FEDEX_1_DAY_FREIGHT"
        FEDEX_2_DAY                                           =    "FEDEX_2_DAY"
        FEDEX_2_DAY_AM                                        =    "FEDEX_2_DAY_AM"
        FEDEX_2_DAY_FREIGHT                                   =    "FEDEX_2_DAY_FREIGHT"
        FEDEX_3_DAY_FREIGHT                                   =    "FEDEX_3_DAY_FREIGHT"
        FEDEX_CARGO_AIRPORT_TO_AIRPORT                        =    "FEDEX_CARGO_AIRPORT_TO_AIRPORT"
        FEDEX_CARGO_FREIGHT_FORWARDING                        =    "FEDEX_CARGO_FREIGHT_FORWARDING"
        FEDEX_CARGO_INTERNATIONAL_EXPRESS_FREIGHT             =    "FEDEX_CARGO_INTERNATIONAL_EXPRESS_FREIGHT"
        FEDEX_CARGO_INTERNATIONAL_PREMIUM                     =    "FEDEX_CARGO_INTERNATIONAL_PREMIUM"
        FEDEX_CARGO_MAIL                                      =    "FEDEX_CARGO_MAIL"
        FEDEX_CARGO_REGISTERED_MAIL                           =    "FEDEX_CARGO_REGISTERED_MAIL"
        FEDEX_CARGO_SURFACE_MAIL                              =    "FEDEX_CARGO_SURFACE_MAIL"
        FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE                    =    "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE"
        FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_EXCLUSIVE_USE      =    "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_EXCLUSIVE_USE"
        FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_NETWORK            =    "FEDEX_CUSTOM_CRITICAL_AIR_EXPEDITE_NETWORK"
        FEDEX_CUSTOM_CRITICAL_CHARTER_AIR                     =    "FEDEX_CUSTOM_CRITICAL_CHARTER_AIR"
        FEDEX_CUSTOM_CRITICAL_POINT_TO_POINT                  =    "FEDEX_CUSTOM_CRITICAL_POINT_TO_POINT"
        FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE                =    "FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE"
        FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE_EXCLUSIVE_USE  =    "FEDEX_CUSTOM_CRITICAL_SURFACE_EXPEDITE_EXCLUSIVE_USE"
        FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_AIR                 =    "FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_AIR"
        FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_VALIDATED_AIR       =    "FEDEX_CUSTOM_CRITICAL_TEMP_ASSURE_VALIDATED_AIR"
        FEDEX_CUSTOM_CRITICAL_WHITE_GLOVE_SERVICES            =    "FEDEX_CUSTOM_CRITICAL_WHITE_GLOVE_SERVICES"
        FEDEX_DISTANCE_DEFERRED                               =    "FEDEX_DISTANCE_DEFERRED"
        FEDEX_EXPRESS_SAVER                                   =    "FEDEX_EXPRESS_SAVER"
        FEDEX_FIRST_FREIGHT                                   =    "FEDEX_FIRST_FREIGHT"
        FEDEX_FREIGHT_ECONOMY                                 =    "FEDEX_FREIGHT_ECONOMY"
        FEDEX_FREIGHT_PRIORITY                                =    "FEDEX_FREIGHT_PRIORITY"
        FEDEX_GROUND                                          =    "FEDEX_GROUND"
        FEDEX_INTERNATIONAL_PRIORITY_PLUS                     =    "FEDEX_INTERNATIONAL_PRIORITY_PLUS"
        FEDEX_NEXT_DAY_AFTERNOON                              =    "FEDEX_NEXT_DAY_AFTERNOON"
        FEDEX_NEXT_DAY_EARLY_MORNING                          =    "FEDEX_NEXT_DAY_EARLY_MORNING"
        FEDEX_NEXT_DAY_END_OF_DAY                             =    "FEDEX_NEXT_DAY_END_OF_DAY"
        FEDEX_NEXT_DAY_FREIGHT                                =    "FEDEX_NEXT_DAY_FREIGHT"
        FEDEX_NEXT_DAY_MID_MORNING                            =    "FEDEX_NEXT_DAY_MID_MORNING"
        FIRST_OVERNIGHT                                       =    "FIRST_OVERNIGHT"
        GROUND_HOME_DELIVERY                                  =    "GROUND_HOME_DELIVERY"
        INTERNATIONAL_DISTRIBUTION_FREIGHT                    =    "INTERNATIONAL_DISTRIBUTION_FREIGHT"
        INTERNATIONAL_ECONOMY                                 =    "INTERNATIONAL_ECONOMY"
        INTERNATIONAL_ECONOMY_DISTRIBUTION                    =    "INTERNATIONAL_ECONOMY_DISTRIBUTION"
        INTERNATIONAL_ECONOMY_FREIGHT                         =    "INTERNATIONAL_ECONOMY_FREIGHT"
        INTERNATIONAL_FIRST                                   =    "INTERNATIONAL_FIRST"
        INTERNATIONAL_GROUND                                  =    "INTERNATIONAL_GROUND"
        INTERNATIONAL_PRIORITY                                =    "INTERNATIONAL_PRIORITY"
        INTERNATIONAL_PRIORITY_DISTRIBUTION                   =    "INTERNATIONAL_PRIORITY_DISTRIBUTION"
        INTERNATIONAL_PRIORITY_EXPRESS                        =    "INTERNATIONAL_PRIORITY_EXPRESS"
        INTERNATIONAL_PRIORITY_FREIGHT                        =    "INTERNATIONAL_PRIORITY_FREIGHT"
        PRIORITY_OVERNIGHT                                    =    "PRIORITY_OVERNIGHT"
        SAME_DAY                                              =    "SAME_DAY"
        SAME_DAY_CITY                                         =    "SAME_DAY_CITY"
        SAME_DAY_METRO_AFTERNOON                              =    "SAME_DAY_METRO_AFTERNOON"
        SAME_DAY_METRO_MORNING                                =    "SAME_DAY_METRO_MORNING"
        SAME_DAY_METRO_RUSH                                   =    "SAME_DAY_METRO_RUSH"
        SMART_POST                                            =    "SMART_POST"
        STANDARD_OVERNIGHT                                    =    "STANDARD_OVERNIGHT"
        TRANSBORDER_DISTRIBUTION_CONSOLIDATION                =    "TRANSBORDER_DISTRIBUTION_CONSOLIDATION"

    class PackagingType(Enum):
        FEDEX_10KG_BOX  =    "FEDEX_10KG_BOX"
        FEDEX_25KG_BOX  =    "FEDEX_25KG_BOX"
        FEDEX_BOX       =    "FEDEX_BOX"
        FEDEX_ENVELOPE  =    "FEDEX_ENVELOPE"
        FEDEX_PAK       =    "FEDEX_PAK"
        FEDEX_TUBE      =    "FEDEX_TUBE"
        YOUR_PACKAGING  =    "YOUR_PACKAGING"

    class PhysicalPackagingType(Enum):
        Bag         =    "BAG" 
        Barrel      =    "BBL" 
        Basket      =    "BSK" 
        Box         =    "BOX" 
        Bucket      =    "BXT"  
        Bundle      =    "BDL" 
        Carton      =    "CTN" 
        Case        =    "CAS" 
        Container   =    "CNT"  
        Crate       =    "CRT" 
        Cylinder    =    "CYL" 
        Drum        =    "DRM" 
        Envelope    =    "ENV"  
        Pail        =    "PAL" 
        Pallet      =    "PLT" 
        Piece       =    "PC "
        Reel        =    "REL" 
        Roll        =    "ROL"
        Skid        =    "SKD" 
        Tank        =    "TNK"
        Tube        =    "TBE"
    
