# Generated by Django 3.2.10 on 2021-12-31 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211231_2353'),
        ('orgs', '0004_auto_20211113_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='orders.order')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='orders',
            field=models.ManyToManyField(related_name='org', through='orgs.OrderLink', to='orders.Order'),
        ),
    ]
