# Generated by Django 3.2.13 on 2022-06-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('orgs', '0005_auto_20211231_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='audit.auditlogentry')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditlog_links', to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='auditlogs',
            field=models.ManyToManyField(related_name='org', through='orgs.AuditLogEntryLink', to='audit.AuditLogEntry'),
        ),
    ]
