# Generated by Django 3.2.13 on 2022-06-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0001_initial'),
        ('orgs', '0006_auto_20220624_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tracing_records',
            field=models.ManyToManyField(related_name='org', to='tracing.TracingRecord'),
        ),
        migrations.CreateModel(
            name='TracingRecordLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='tracing.tracingrecord')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_record_links', to='orgs.organization')),
            ],
        ),
    ]
