# Generated by Django 4.1.3 on 2022-11-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documenttemplate_active"),
        ("orgs", "0010_appinstallationlink_applink_batchoperationlink_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplateLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="documents.documenttemplate",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_template_links",
                        to="orgs.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="document_templates",
            field=models.ManyToManyField(
                related_name="org",
                through="orgs.DocumentTemplateLink",
                to="documents.documenttemplate",
            ),
        ),
    ]
