# Generated by Django 4.2.8 on 2023-12-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0059_ratesheet"),
        ("orgs", "0013_carrierconfiglink_organization_carrier_configs"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateSheetLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="providers.ratesheet",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_sheet_links",
                        to="orgs.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="rate_sheets",
            field=models.ManyToManyField(
                related_name="org",
                through="orgs.RateSheetLink",
                to="providers.ratesheet",
            ),
        ),
    ]
