# Generated by Django 4.2.8 on 2024-01-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_metafield"),
        ("orgs", "0015_workflowtriggerlink_workflowlink_workfloweventlink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="metafields",
            field=models.ManyToManyField(related_name="org", to="core.metafield"),
        ),
    ]
