# Generated by Django 4.2.10 on 2024-03-18 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0058_manifest_shipment_manifest"),
        ("orgs", "0017_organization_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManifestLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="manager.manifest",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifest_links",
                        to="orgs.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="manifests",
            field=models.ManyToManyField(
                related_name="org", through="orgs.ManifestLink", to="manager.manifest"
            ),
        ),
    ]
