# Generated by Django 5.2.1 on 2025-06-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_shippingrule"),
        ("orgs", "0019_organizationinvitation_is_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRuleLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="automation.shippingrule",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_rule_links",
                        to="orgs.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="shipping_rules",
            field=models.ManyToManyField(
                related_name="org",
                through="orgs.ShippingRuleLink",
                to="automation.shippingrule",
            ),
        ),
    ]
