# Generated by Django 4.1.6 on 2023-02-09 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_remove_order_order_id_idx_alter_order_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipments",
        ),
    ]
