# Generated by Django 3.2.12 on 2022-03-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documenttemplate_related_objects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='related_objects',
            new_name='related_object',
        ),
    ]
