# Generated by Django 3.2.13 on 2022-06-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_related_objects_documenttemplate_related_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='active',
            field=models.BooleanField(default=True, help_text='disable template flag. to filter out from active document downloads'),
        ),
    ]
