# Generated by Django 4.1.3 on 2022-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documenttemplate_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="description",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
