# Generated by Django 3.2.11 on 2022-03-04 16:59

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Order = apps.get_model("orders", "Order")

    Order.objects.using(db_alias).filter(status="created").update(status="unfulfilled")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_line_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unfulfilled", "unfulfilled"),
                    ("cancelled", "cancelled"),
                    ("fulfilled", "fulfilled"),
                    ("delivered", "delivered"),
                    ("partial", "partial"),
                ],
                default="unfulfilled",
                max_length=25,
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
