# Generated by Django 3.1.8 on 2021-04-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_auto_20210409_0852'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fedexsettings',
            table='fedex-settings',
        ),
        migrations.AlterModelTable(
            name='upssettings',
            table='ups-settings',
        ),
    ]
