# Generated by Django 3.1.6 on 2021-02-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20210212_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='AustraliaPostSettings',
            fields=[
                ('carrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.carrier')),
                ('api_key', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Australia Post Settings',
                'verbose_name_plural': 'Australia Post Settings',
                'db_table': 'australia-post-settings',
            },
            bases=('providers.carrier',),
        ),
    ]
