# Generated by Django 4.2.10 on 2024-03-12 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import karrio.server.core.models
import karrio.server.core.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_token_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            karrio.server.core.models.base.uuid,
                            *(),
                            **{"prefix": "wcfg_"}
                        ),
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": {}}
                        )
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Config",
                "verbose_name_plural": "Workspace Configs",
                "db_table": "workspace-config",
            },
            bases=(karrio.server.core.models.base.ControlledAccessModel, models.Model),
        ),
    ]
