# Generated by Django 5.2.5 on 2025-08-23 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracing", "0006_alter_tracingrecord_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tracingrecord",
            index=models.Index(fields=["created_at"], name="tracing_created_at_idx"),
        ),
    ]
