# Generated by Django 3.2 on 2021-04-26 19:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20210403_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customs',
            name='duty',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
