# Generated by Django 3.2 on 2021-04-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20210427_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='customs',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
