# Generated by Django 3.2.3 on 2021-05-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_customs_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
