# Generated by Django 3.2.3 on 2021-06-01 03:40

from django.db import migrations, models
import functools
import purpleserver.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20210515_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='validation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customs',
            name='duty',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': None}), null=True),
        ),
        migrations.AlterField(
            model_name='customs',
            name='options',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': {}}), null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='options',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': {}}), null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickup_charge',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='messages',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': []}), null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='meta',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': {}}), null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='options',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': {}}), null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': None}), null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='rates',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': []}), null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='selected_rate',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='services',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': []}), null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='events',
            field=models.JSONField(blank=True, default=functools.partial(purpleserver.core.utils.identity, *(), **{'value': []}), null=True),
        ),
    ]
