# Generated by Django 4.1.3 on 2022-12-10 16:20

from django.db import migrations, models
import django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ("tracing", "0003_auto_20221105_0317"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tracingrecord",
            index=models.Index(
                django.db.models.fields.json.KeyTextTransform(
                    "carrier_account_id", "meta"
                ),
                condition=models.Q(("meta__carrier_account_id__isnull", False)),
                name="carrier_account_idx",
            ),
        ),
    ]
