from .rate import CarrierNameMapperPartial as CarrierNameQuoteMapperPartial
from .track import CarrierNameMapperPartial as CarrierNameTrackMapperPartial
from .shipment import CarrierNameMapperPartial as CarrierNameShipmentMapperPartial
from .pickup import CarrierNameMapperPartial as CarrierNamePickupMapperPartial
