from karrio_cli.templates.address import *
from karrio_cli.templates.docs import *
from karrio_cli.templates.documents import *
from karrio_cli.templates.manifest import *
from karrio_cli.templates.pickup import *
from karrio_cli.templates.rates import *
from karrio_cli.templates.sdk import *
from karrio_cli.templates.shipments import *
from karrio_cli.templates.tracking import *
