# Generated by Django 3.2.4 on 2021-06-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0016_alter_purolatorsettings_user_token"),
        ("pricing", "0011_auto_20210615_1601"),
    ]

    operations = [
        migrations.AddField(
            model_name="surcharge",
            name="carrier_accounts",
            field=models.ManyToManyField(
                blank=True,
                help_text="\n        The list of carrier accounts you want to apply the surcharge to.\n        <br/>\n        Note that by default, the surcharge is applied to all carrier accounts\n        ",
                to="providers.Carrier",
            ),
        ),
    ]
