# Generated by Django 3.2.8 on 2021-10-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0013_alter_surcharge_services"),
    ]

    operations = []
