# Generated by Django 4.2.1 on 2023-06-04 15:44

from django.db import migrations
import karrio.server.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0034_alter_surcharge_carriers_alter_surcharge_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surcharge",
            name="carriers",
            field=karrio.server.core.fields.MultiChoiceField(
                blank=True,
                choices=[
                    ("amazon_mws", "amazon_mws"),
                    ("aramex", "aramex"),
                    ("australiapost", "australiapost"),
                    ("boxknight", "boxknight"),
                    ("canadapost", "canadapost"),
                    ("canpar", "canpar"),
                    ("chronopost", "chronopost"),
                    ("dhl_express", "dhl_express"),
                    ("dhl_poland", "dhl_poland"),
                    ("dhl_universal", "dhl_universal"),
                    ("dicom", "dicom"),
                    ("dpd", "dpd"),
                    ("dpdhl", "dpdhl"),
                    ("easypost", "easypost"),
                    ("eshipper", "eshipper"),
                    ("fedex", "fedex"),
                    ("freightcom", "freightcom"),
                    ("generic", "generic"),
                    ("geodis", "geodis"),
                    ("laposte", "laposte"),
                    ("nationex", "nationex"),
                    ("purolator", "purolator"),
                    ("roadie", "roadie"),
                    ("royalmail", "royalmail"),
                    ("sendle", "sendle"),
                    ("sf_express", "sf_express"),
                    ("tnt", "tnt"),
                    ("ups", "ups"),
                    ("usps", "usps"),
                    ("usps_international", "usps_international"),
                    ("yanwen", "yanwen"),
                    ("yunexpress", "yunexpress"),
                ],
                help_text="\n        The list of carriers you want to apply the surcharge to.\n        <br/>\n        Note that by default, the surcharge is applied to all carriers\n        ",
                null=True,
            ),
        ),
    ]
