# Generated by Django 4.1.3 on 2022-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_auto_20221130_0255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
