# Generated by Django 5.2.5 on 2025-08-23 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_webhook_enabled_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_at"], name="event_created_at_idx"),
        ),
    ]
