{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karrio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karrio.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.config.secretKey | b64enc | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
{{- end }}
