# Generated by Django 4.1 on 2022-10-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datatemplatelink",
            name="item",
        ),
        migrations.RemoveField(
            model_name="datatemplatelink",
            name="org",
        ),
        migrations.RemoveField(
            model_name="batchoperation",
            name="org",
        ),
        migrations.RemoveField(
            model_name="datatemplate",
            name="org",
        ),
        migrations.DeleteModel(
            name="BatchOperationLink",
        ),
        migrations.DeleteModel(
            name="DataTemplateLink",
        ),
    ]
