# Generated by Django 3.2.1 on 2021-05-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_auto_20210409_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['test', '-created_at']},
        ),
    ]
