# Generated by Django 5.2.7 on 2025-10-14 01:00

import functools
import karrio.server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0021_remove_organization_installations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="metadata",
            field=models.JSONField(
                default=functools.partial(
                    karrio.server.core.models._identity, *(), **{"value": {}}
                ),
                help_text="Organization defined metadata",
            ),
        ),
    ]
