# Generated by Django 3.2.11 on 2022-03-14 14:49

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import purplship.server.core.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0005_auto_20211231_2353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=functools.partial(purplship.server.core.models.base.uuid, *(), **{'prefix': 'doc_'}), editable=False, max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$')])),
                ('name', models.CharField(max_length=50)),
                ('template', models.TextField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('related_objects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'db_table': 'document-template',
                'ordering': ['-created_at'],
            },
            bases=(purplship.server.core.models.base.ControlledAccessModel, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentTemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='documents.documenttemplate')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_template_links', to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='org',
            field=models.ManyToManyField(related_name='document_templates', through='documents.DocumentTemplateLink', to='orgs.Organization'),
        ),
    ]
