# Generated by Django 3.2.12 on 2022-04-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0028_auto_20220323_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyPostSettings',
            fields=[
                ('carrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.carrier')),
                ('api_key', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'EasyPost Settings',
                'verbose_name_plural': 'EasyPost Settings',
                'db_table': 'easypost-settings',
            },
            bases=('providers.carrier',),
        ),
    ]
