# Generated by Django 3.2.13 on 2022-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0031_delete_amazonmwssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='test',
            field=models.BooleanField(db_column='test_mode', default=True, help_text='Toggle carrier connection mode'),
        ),
    ]
