# Generated by Django 4.1.6 on 2023-02-04 09:43

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0043_alter_genericsettings_account_number_and_more"),
    ]

    operations = []

    if "postgres" in settings.DB_ENGINE:
        operations = [
            migrations.RunSQL('ALTER TABLE "providers_carrier" ALTER COLUMN "capabilities" TYPE jsonb USING to_jsonb(capabilities)'),
        ]
