# Generated by Django 4.1.5 on 2023-01-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0045_alter_carrier_active_alter_carrier_carrier_id"),
    ]

    operations = []
