# Generated by Django 4.2.5 on 2023-09-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0053_locate2usettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zoom2uSettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("api_key", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Zoom2u Settings",
                "verbose_name_plural": "Zoom2u Settings",
                "db_table": "zoom2u-settings",
            },
            bases=("providers.carrier",),
        ),
    ]
