# Generated by Django 3.2.4 on 2021-06-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_tntsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPSInternationalSettings',
            fields=[
                ('carrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.carrier')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mailer_id', models.CharField(max_length=200, null=True)),
                ('customer_registration_id', models.CharField(max_length=200, null=True)),
                ('logistics_manager_mailer_id', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'USPS International Settings',
                'verbose_name_plural': 'USPS International Settings',
                'db_table': 'usps_international-settings',
            },
            bases=('providers.carrier',),
        ),
        migrations.AddField(
            model_name='uspssettings',
            name='customer_registration_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uspssettings',
            name='logistics_manager_mailer_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uspssettings',
            name='mailer_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
