# Generated by Django 4.1.7 on 2023-03-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0045_alter_carrier_active_alter_carrier_carrier_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dpdhlsettings",
            name="signature",
        ),
        migrations.AddField(
            model_name="dpdhlsettings",
            name="app_token",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dpdhlsettings",
            name="zt_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dpdhlsettings",
            name="zt_password",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dpdhlsettings",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dpdhlsettings",
            name="app_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
