# Generated by Django 4.2.1 on 2023-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0050_carrier_is_system_alter_carrier_metadata_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upssettings",
            old_name="username",
            new_name="client_id",
        ),
        migrations.RenameField(
            model_name="upssettings",
            old_name="password",
            new_name="client_secret",
        ),
        migrations.RemoveField(
            model_name="upssettings",
            name="access_license_number",
        ),
        migrations.AlterField(
            model_name="upssettings",
            name="account_number",
            field=models.CharField(max_length=100),
        ),
    ]
