# Generated by Django 4.2.4 on 2023-09-03 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0054_zoom2usettings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AmazonMwsSettings",
            new_name="AmazonShippingSettings",
        ),
        migrations.RemoveField(
            model_name="yanwensettings",
            name="carrier_ptr",
        ),
        migrations.RemoveField(
            model_name="yunexpresssettings",
            name="carrier_ptr",
        ),
        migrations.AlterModelOptions(
            name="amazonshippingsettings",
            options={
                "verbose_name": "Amazon Shipping Settings",
                "verbose_name_plural": "Amazon Shipping Settings",
            },
        ),
        migrations.AlterModelTable(
            name="amazonshippingsettings",
            table="amazon_shipping-settings",
        ),
        migrations.DeleteModel(
            name="SFExpressSettings",
        ),
        migrations.DeleteModel(
            name="YanwenSettings",
        ),
        migrations.DeleteModel(
            name="YunExpressSettings",
        ),
    ]
