# Generated by Django 4.2.8 on 2023-12-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0058_morneausettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="morneausettings",
            name="billed_id",
            field=models.IntegerField(),
        ),
    ]
