# Generated by Django 4.2.8 on 2023-12-17 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import karrio.server.core.models
import karrio.server.core.models.base


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("providers", "0058_alliedexpresssettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateSheet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            karrio.server.core.models.base.uuid,
                            *(),
                            **{"prefix": "rsht_"}
                        ),
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=50, verbose_name="name"),
                ),
                (
                    "slug",
                    models.CharField(db_index=True, max_length=50, verbose_name="slug"),
                ),
                ("carrier_name", models.CharField(db_index=True, max_length=50)),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": {}}
                        ),
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="service_sheet",
                        to="providers.servicelevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Sheet",
                "verbose_name_plural": "Rate Sheets",
                "db_table": "rate-sheet",
                "ordering": ["-created_at"],
            },
            bases=(karrio.server.core.models.base.ControlledAccessModel, models.Model),
        ),
    ]
