# Generated by Django 4.2.8 on 2024-01-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0059_alter_morneausettings_billed_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="morneausettings",
            name="caller_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
