# Generated by Django 4.2.8 on 2024-01-09 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0060_morneausettings_caller_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="morneausettings",
            name="billed_id",
        ),
    ]
