# Generated by Django 4.2.8 on 2024-01-25 00:52

from django.db import migrations, models
import functools
import karrio.server.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0062_sendlesettings_account_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelevel",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.models._identity, *(), **{"value": {}}
                ),
                null=True,
            ),
        ),
    ]
