# Generated by Django 4.2.8 on 2024-02-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0063_servicelevel_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlliedExpressLocalSettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("account", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Allied Express Local Settings",
                "verbose_name_plural": "Allied Express Local Settings",
                "db_table": "allied-express-local-settings",
            },
            bases=("providers.carrier",),
        ),
    ]
