# Generated by Django 4.2.8 on 2024-02-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0064_alliedexpresslocalsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeutschePostSettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("dhl_api_key", models.CharField(max_length=200)),
                (
                    "tracking_consumer_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "tracking_consumer_secret",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_number",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "rate_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="providers.ratesheet",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(blank=True, to="providers.servicelevel"),
                ),
            ],
            options={
                "verbose_name": "Deutsche Post Settings",
                "verbose_name_plural": "Deutsche Post Settings",
                "db_table": "deutschepost-settings",
            },
            bases=("providers.carrier",),
        ),
    ]
