# Generated by Django 4.2.8 on 2024-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0065_deutschepostsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelevel",
            name="carrier_service_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
