# Generated by Django 4.2.14 on 2024-07-27 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0072_rename_eshippersettings_eshipperxmlsettings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eshipperxmlsettings",
            options={
                "verbose_name": "eShipper Settings",
                "verbose_name_plural": "eShipper Settings",
            },
        ),
        migrations.RemoveField(
            model_name="eshipperxmlsettings",
            name="password",
        ),
        migrations.RemoveField(
            model_name="eshipperxmlsettings",
            name="username",
        ),
        migrations.AddField(
            model_name="eshipperxmlsettings",
            name="credential",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eshipperxmlsettings",
            name="principal",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
