# Generated by Django 4.2.11 on 2024-06-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0072_haypostsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="haypostsettings",
            name="account",
        ),
        migrations.RemoveField(
            model_name="haypostsettings",
            name="service_type",
        ),
        migrations.AddField(
            model_name="haypostsettings",
            name="customerId",
            field=models.PositiveBigIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="haypostsettings",
            name="customerType",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
