# Generated by Django 5.1.9 on 2025-05-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0080_alter_aramexsettings_account_country_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fedexwssettings",
            name="carrier_ptr",
        ),
        migrations.RemoveField(
            model_name="uspswtinternationalsettings",
            name="carrier_ptr",
        ),
        migrations.RemoveField(
            model_name="uspswtsettings",
            name="carrier_ptr",
        ),
        migrations.DeleteModel(
            name="DPDHLSettings",
        ),
        migrations.DeleteModel(
            name="FedexWSSettings",
        ),
        migrations.DeleteModel(
            name="USPSWTInternationalSettings",
        ),
        migrations.DeleteModel(
            name="USPSWTSettings",
        ),
    ]
