# Generated by Django 4.2.16 on 2025-01-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0080_alter_aramexsettings_account_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freightcomsettings",
            name="api_key",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
