# Generated by Django migration to populate missing required credentials for DHL Parcel DE
# This migration ensures existing dhl_parcel_de connections have all required fields
# (username, password, client_id, client_secret) to prevent initialization errors
# after the settings schema was updated.

from django.db import migrations
from django.utils import timezone


# Required fields for dhl_parcel_de that have no default values
REQUIRED_FIELDS = ["username", "password", "client_id", "client_secret"]


def populate_dhl_parcel_de_required_credentials(apps, schema_editor):
    """
    Find all dhl_parcel_de carrier connections that are missing required fields
    and populate them with placeholder timestamp values.
    """
    Carrier = apps.get_model("providers", "Carrier")
    db_alias = schema_editor.connection.alias

    # Find all dhl_parcel_de carriers
    dhl_parcel_de_carriers = Carrier.objects.using(db_alias).filter(
        carrier_code="dhl_parcel_de"
    )

    timestamp = timezone.now().strftime("%Y%m%d%H%M%S")

    for carrier in dhl_parcel_de_carriers:
        credentials = carrier.credentials or {}
        updated = False

        # Check and populate all missing required fields
        for field in REQUIRED_FIELDS:
            if not credentials.get(field):
                credentials[field] = f"PLACEHOLDER_{timestamp}"
                updated = True

        if updated:
            carrier.credentials = credentials
            carrier.save(using=db_alias, update_fields=["credentials"])


def reverse_dhl_parcel_de_required_credentials(apps, schema_editor):
    """
    Remove placeholder credentials (for rollback).
    Only removes credentials that were set by this migration (contain PLACEHOLDER_).
    """
    Carrier = apps.get_model("providers", "Carrier")
    db_alias = schema_editor.connection.alias

    dhl_parcel_de_carriers = Carrier.objects.using(db_alias).filter(
        carrier_code="dhl_parcel_de"
    )

    for carrier in dhl_parcel_de_carriers:
        credentials = carrier.credentials or {}
        updated = False

        # Only remove if it's a placeholder value
        for field in REQUIRED_FIELDS:
            if credentials.get(field, "").startswith("PLACEHOLDER_"):
                del credentials[field]
                updated = True

        if updated:
            carrier.credentials = credentials
            carrier.save(using=db_alias, update_fields=["credentials"])


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0084_alter_servicelevel_currency"),
    ]

    operations = [
        migrations.RunPython(
            populate_dhl_parcel_de_required_credentials,
            reverse_dhl_parcel_de_required_credentials,
        ),
    ]
