# Generated by Django migration to rename customer_number to billing_number
# for DHL Parcel DE connections. This keeps existing configuration values
# when the field was renamed in the settings schema.

from django.db import migrations


def rename_customer_number_to_billing_number(apps, schema_editor):
    """
    Find all dhl_parcel_de carrier connections that have customer_number
    and rename it to billing_number to preserve the configuration value.
    """
    Carrier = apps.get_model("providers", "Carrier")
    db_alias = schema_editor.connection.alias

    # Find all dhl_parcel_de carriers
    dhl_parcel_de_carriers = Carrier.objects.using(db_alias).filter(
        carrier_code="dhl_parcel_de"
    )

    for carrier in dhl_parcel_de_carriers:
        credentials = carrier.credentials or {}

        # Check if customer_number exists and billing_number doesn't
        if credentials.get("customer_number") and not credentials.get("billing_number"):
            # Copy customer_number value to billing_number
            credentials["billing_number"] = credentials["customer_number"]
            # Remove old customer_number field
            del credentials["customer_number"]

            carrier.credentials = credentials
            carrier.save(using=db_alias, update_fields=["credentials"])


def rename_billing_number_to_customer_number(apps, schema_editor):
    """
    Reverse migration: rename billing_number back to customer_number.
    """
    Carrier = apps.get_model("providers", "Carrier")
    db_alias = schema_editor.connection.alias

    dhl_parcel_de_carriers = Carrier.objects.using(db_alias).filter(
        carrier_code="dhl_parcel_de"
    )

    for carrier in dhl_parcel_de_carriers:
        credentials = carrier.credentials or {}

        # Check if billing_number exists and customer_number doesn't
        if credentials.get("billing_number") and not credentials.get("customer_number"):
            # Copy billing_number value back to customer_number
            credentials["customer_number"] = credentials["billing_number"]
            # Remove the billing_number field
            del credentials["billing_number"]

            carrier.credentials = credentials
            carrier.save(using=db_alias, update_fields=["credentials"])


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0085_populate_dhl_parcel_de_oauth_credentials"),
    ]

    operations = [
        migrations.RunPython(
            rename_customer_number_to_billing_number,
            rename_billing_number_to_customer_number,
        ),
    ]
