# Generated by Django - Add cost and max_volume fields to ServiceLevel

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0088_servicelevel_surcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelevel',
            name='cost',
            field=models.FloatField(
                blank=True,
                null=True,
                help_text='Base COGS (Cost of Goods Sold) - internal cost tracking',
            ),
        ),
        migrations.AddField(
            model_name='servicelevel',
            name='max_volume',
            field=models.FloatField(
                blank=True,
                null=True,
                help_text='Maximum volume in liters for volumetric weight calculation',
            ),
        ),
    ]
