# Generated by Django - Add surcharges to RateSheet and zone_ids/surcharge_ids to ServiceLevel

from django.db import migrations, models
import karrio.server.core.models as core


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0089_servicelevel_cost_max_volume'),
    ]

    operations = [
        # Add surcharges field to RateSheet (shared surcharge definitions)
        migrations.AddField(
            model_name='ratesheet',
            name='surcharges',
            field=models.JSONField(
                blank=True,
                null=True,
                default=core.field_default([]),
                help_text="Shared surcharge definitions: [{'id': 'surch_1', 'name': 'Fuel', 'amount': 8.5, 'surcharge_type': 'percentage'}]",
            ),
        ),
        # Add zone_ids to ServiceLevel (references shared zones)
        migrations.AddField(
            model_name='servicelevel',
            name='zone_ids',
            field=models.JSONField(
                blank=True,
                null=True,
                default=core.field_default([]),
                help_text="List of zone IDs this service applies to: ['zone_1', 'zone_2']",
            ),
        ),
        # Add surcharge_ids to ServiceLevel (references shared surcharges)
        migrations.AddField(
            model_name='servicelevel',
            name='surcharge_ids',
            field=models.JSONField(
                blank=True,
                null=True,
                default=core.field_default([]),
                help_text="List of surcharge IDs to apply: ['surch_fuel', 'surch_residential']",
            ),
        ),
    ]
