# Generated by Django - Migrate legacy zones/surcharges to shared format and remove legacy fields

from django.db import migrations, models


def migrate_legacy_to_shared_format(apps, schema_editor):
    """
    Migrate legacy per-service zones and surcharges to the new shared format.

    Legacy format:
    - ServiceLevel.zones: [{'label': 'Zone 1', 'rate': 10.0, 'country_codes': [...], ...}]
    - ServiceLevel.surcharges: [{'name': 'Fuel', 'amount': 5.0, 'surcharge_type': 'percentage'}]

    New format:
    - RateSheet.zones: [{'id': 'zone_1', 'label': 'Zone 1', 'country_codes': [...]}]
    - RateSheet.surcharges: [{'id': 'surch_1', 'name': 'Fuel', 'amount': 5.0, ...}]
    - RateSheet.service_rates: [{'service_id': 'svc_1', 'zone_id': 'zone_1', 'rate': 10.0}]
    - ServiceLevel.zone_ids: ['zone_1', 'zone_2']
    - ServiceLevel.surcharge_ids: ['surch_1']
    """
    RateSheet = apps.get_model('providers', 'RateSheet')

    for rate_sheet in RateSheet.objects.all():
        # Skip if already migrated (has zones or service_rates)
        if rate_sheet.zones or rate_sheet.service_rates:
            continue

        all_zones = {}
        all_surcharges = {}
        service_rates = []
        zone_counter = 1
        surcharge_counter = 1

        # Process each service in the rate sheet
        for service in rate_sheet.services.all():
            legacy_zones = service.zones or []
            legacy_surcharges = service.surcharges or []

            service_zone_ids = []
            service_surcharge_ids = []

            # Process zones
            for zone_data in legacy_zones:
                # Create zone signature for deduplication
                # Use `or []` to handle None values
                cities = zone_data.get('cities') or []
                postal_codes = zone_data.get('postal_codes') or []
                country_codes = zone_data.get('country_codes') or []

                zone_signature = {
                    'label': zone_data.get('label') or f'Zone {zone_counter}',
                    'cities': sorted(cities),
                    'postal_codes': sorted(postal_codes),
                    'country_codes': sorted(country_codes),
                }
                sig_key = str(zone_signature)

                if sig_key not in all_zones:
                    zone_id = f"zone_{zone_counter}"
                    all_zones[sig_key] = {
                        'id': zone_id,
                        'label': zone_signature['label'],
                        'cities': cities,
                        'postal_codes': postal_codes,
                        'country_codes': country_codes,
                        'transit_days': zone_data.get('transit_days'),
                        'transit_time': zone_data.get('transit_time'),
                        'radius': zone_data.get('radius'),
                        'latitude': zone_data.get('latitude'),
                        'longitude': zone_data.get('longitude'),
                    }
                    zone_counter += 1

                zone_id = all_zones[sig_key]['id']
                service_zone_ids.append(zone_id)

                # Create service rate record
                service_rates.append({
                    'service_id': service.id,
                    'zone_id': zone_id,
                    'rate': zone_data.get('rate', 0),
                    'cost': zone_data.get('cost'),
                    'min_weight': zone_data.get('min_weight'),
                    'max_weight': zone_data.get('max_weight'),
                    'transit_days': zone_data.get('transit_days'),
                    'transit_time': zone_data.get('transit_time'),
                })

            # Process surcharges
            for surcharge_data in legacy_surcharges:
                # Create surcharge signature for deduplication
                surcharge_signature = {
                    'name': surcharge_data.get('name', f'Surcharge {surcharge_counter}'),
                    'amount': surcharge_data.get('amount', 0),
                    'surcharge_type': surcharge_data.get('surcharge_type', 'fixed'),
                }
                sig_key = str(surcharge_signature)

                if sig_key not in all_surcharges:
                    surcharge_id = f"surch_{surcharge_counter}"
                    all_surcharges[sig_key] = {
                        'id': surcharge_id,
                        'name': surcharge_signature['name'],
                        'amount': surcharge_signature['amount'],
                        'surcharge_type': surcharge_signature['surcharge_type'],
                        'cost': surcharge_data.get('cost'),
                        'active': surcharge_data.get('active', True),
                    }
                    surcharge_counter += 1

                surcharge_id = all_surcharges[sig_key]['id']
                service_surcharge_ids.append(surcharge_id)

            # Update service with zone_ids and surcharge_ids
            service.zone_ids = list(set(service_zone_ids))  # Deduplicate
            service.surcharge_ids = list(set(service_surcharge_ids))  # Deduplicate
            service.save(update_fields=['zone_ids', 'surcharge_ids'])

        # Save shared zones and surcharges to rate sheet
        if all_zones or service_rates:
            rate_sheet.zones = list(all_zones.values())
            rate_sheet.service_rates = service_rates
            rate_sheet.surcharges = list(all_surcharges.values())
            rate_sheet.save(update_fields=['zones', 'service_rates', 'surcharges'])


def reverse_migration(apps, schema_editor):
    """
    Reverse migration is a no-op since we're not deleting the legacy data,
    just adding new fields. The legacy fields will be removed in a separate migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0090_ratesheet_surcharges_servicelevel_zone_surcharge_ids'),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(migrate_legacy_to_shared_format, reverse_migration),

        # Then remove the legacy fields from ServiceLevel
        migrations.RemoveField(
            model_name='servicelevel',
            name='zones',
        ),
        migrations.RemoveField(
            model_name='servicelevel',
            name='surcharges',
        ),
    ]
