# Generated by Django 5.2.10 on 2026-01-20 23:54
# Modified to split: Add new models first, defer field removal to post-migration

import django.db.models.deletion
import functools
import karrio.server.core.fields
import karrio.server.core.models
import karrio.server.core.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Step 1: Add SystemConnection, BrokeredConnection models and add config field to Carrier.

    This migration DOES NOT remove is_system or active_users yet.
    Those fields are needed by the data migration (0093) to migrate existing data.
    Field removal happens in migration 0094 after data is migrated.
    """

    dependencies = [
        ("providers", "0091_migrate_legacy_zones_surcharges"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create SystemConnection model
        migrations.CreateModel(
            name="SystemConnection",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            karrio.server.core.models.base.uuid,
                            *(),
                            **{"prefix": "sys_"}
                        ),
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "carrier_code",
                    models.CharField(
                        db_index=True,
                        help_text="Carrier identifier (e.g., 'dhl_express', 'fedex')",
                        max_length=100,
                    ),
                ),
                (
                    "carrier_id",
                    models.CharField(
                        db_index=True,
                        help_text="Platform-defined connection identifier",
                        max_length=150,
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": {}}
                        ),
                        help_text="Carrier API credentials (admin only)",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": {}}
                        ),
                        help_text="Base operational configuration",
                    ),
                ),
                (
                    "capabilities",
                    karrio.server.core.fields.MultiChoiceField(
                        choices=[
                            ("pickup", "pickup"),
                            ("rating", "rating"),
                            ("shipping", "shipping"),
                            ("tracking", "tracking"),
                            ("paperless", "paperless"),
                            ("manifest", "manifest"),
                            ("duties", "duties"),
                            ("insurance", "insurance"),
                            ("webhook", "webhook"),
                            ("oauth", "oauth"),
                        ],
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": []}
                        ),
                        help_text="Enabled carrier capabilities",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable/disable system connection (affects all brokered)",
                    ),
                ),
                (
                    "test_mode",
                    models.BooleanField(
                        default=True, help_text="Toggle carrier connection mode"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": {}}
                        ),
                        help_text="Admin-defined metadata",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this connection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_connections_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rate_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_connections",
                        to="providers.ratesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Connection",
                "verbose_name_plural": "System Connections",
                "db_table": "system_connection",
                "ordering": ["test_mode", "-created_at"],
            },
        ),
        # Create BrokeredConnection model
        migrations.CreateModel(
            name="BrokeredConnection",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            karrio.server.core.models.base.uuid,
                            *(),
                            **{"prefix": "brk_"}
                        ),
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "carrier_id",
                    models.CharField(
                        blank=True,
                        help_text="User-defined carrier identifier (overrides system)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "config_overrides",
                    models.JSONField(
                        blank=True,
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": {}}
                        ),
                        help_text="User-specific config overrides (merged with system config)",
                    ),
                ),
                (
                    "capabilities_overrides",
                    karrio.server.core.fields.MultiChoiceField(
                        blank=True,
                        choices=[
                            ("pickup", "pickup"),
                            ("rating", "rating"),
                            ("shipping", "shipping"),
                            ("tracking", "tracking"),
                            ("paperless", "paperless"),
                            ("manifest", "manifest"),
                            ("duties", "duties"),
                            ("insurance", "insurance"),
                            ("webhook", "webhook"),
                            ("oauth", "oauth"),
                        ],
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": []}
                        ),
                        help_text="Override capabilities (if empty, uses system capabilities)",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="User-level enable/disable",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=functools.partial(
                            karrio.server.core.models._identity, *(), **{"value": {}}
                        ),
                        help_text="User-defined metadata",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who enabled this connection (OSS mode)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokered_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system_connection",
                    models.ForeignKey(
                        help_text="The system connection this is based on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokered_connections",
                        to="providers.systemconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brokered Connection",
                "verbose_name_plural": "Brokered Connections",
                "db_table": "brokered_connection",
                "ordering": ["-created_at"],
            },
        ),
        # Add config field to Carrier (but keep is_system and active_users for now)
        migrations.AddField(
            model_name="carrier",
            name="config",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.models._identity, *(), **{"value": {}}
                ),
                help_text="Operational configuration",
            ),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name="systemconnection",
            index=models.Index(
                fields=["carrier_code", "active"],
                name="system_conn_carrier_53d940_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokeredconnection",
            index=models.Index(
                fields=["is_enabled"], name="brokered_co_is_enab_01b94b_idx"
            ),
        ),
    ]
