# Generated by Django 6.0 on 2026-01-22
# Adds dim_factor and use_volumetric fields to ServiceLevel
# for volumetric/dimensional weight calculation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0096_ratesheet_origin_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelevel",
            name="dim_factor",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Dimensional weight divisor. 5000-6000 for cm/kg, 139-166 for in/lb",
            ),
        ),
        migrations.AddField(
            model_name="servicelevel",
            name="use_volumetric",
            field=models.BooleanField(
                default=False,
                help_text="Use max(actual_weight, volumetric_weight) for rate calculation",
            ),
        ),
    ]
