# Generated by Django 6.0 on 2026-01-22
# Adds features field to ServiceLevel for structured service features:
# first_mile, last_mile, form_factor, b2c, b2b, shipment_type, age_check, etc.

from django.db import migrations, models

import karrio.server.core.models as core


def convert_features_array_to_object(apps, schema_editor):
    """Convert legacy array-based features to structured object format.

    Legacy format: ["tracked", "b2c", "first_mile", "service_point"]
    New format: {"tracked": true, "b2c": true, "first_mile": "drop_off", "last_mile": "service_point"}
    """
    ServiceLevel = apps.get_model("providers", "ServiceLevel")

    # Mapping from legacy array values to structured object fields
    boolean_features = {
        "tracked",
        "b2c",
        "b2b",
        "signature",
        "insurance",
        "express",
        "dangerous_goods",
        "saturday_delivery",
        "sunday_delivery",
        "multicollo",
        "neighbor_delivery",
    }

    first_mile_mapping = {
        "first_mile": "drop_off",  # Default when only "first_mile" is present
        "pick_up": "pick_up",
        "drop_off": "drop_off",
        "pick_up_and_drop_off": "pick_up_and_drop_off",
    }

    last_mile_mapping = {
        "last_mile": "home_delivery",  # Default when only "last_mile" is present
        "home_delivery": "home_delivery",
        "service_point": "service_point",
        "mailbox": "mailbox",
    }

    form_factor_mapping = {
        "letter": "letter",
        "parcel": "parcel",
        "pallet": "pallet",
    }

    for service in ServiceLevel.objects.all():
        features = service.features

        # Skip if already an object, empty, or not a list
        if not features or isinstance(features, dict) or not isinstance(features, list):
            continue

        new_features = {}

        for feature in features:
            if feature in boolean_features:
                new_features[feature] = True
            elif feature in first_mile_mapping:
                new_features["first_mile"] = first_mile_mapping[feature]
            elif feature in last_mile_mapping:
                new_features["last_mile"] = last_mile_mapping[feature]
            elif feature in form_factor_mapping:
                new_features["form_factor"] = form_factor_mapping[feature]
            elif feature == "outbound":
                new_features["shipment_type"] = "outbound"
            elif feature == "returns":
                new_features["shipment_type"] = "returns"

        service.features = new_features
        service.save(update_fields=["features"])


def revert_features_object_to_array(apps, schema_editor):
    """Revert structured object features back to array format."""
    ServiceLevel = apps.get_model("providers", "ServiceLevel")

    for service in ServiceLevel.objects.all():
        features = service.features

        # Skip if already an array, empty, or not a dict
        if not features or isinstance(features, list) or not isinstance(features, dict):
            continue

        new_features = []

        for key, value in features.items():
            if isinstance(value, bool) and value:
                new_features.append(key)
            elif isinstance(value, str) and value:
                new_features.append(value)

        service.features = new_features
        service.save(update_fields=["features"])


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0097_servicelevel_volumetric_weight_fields"),
    ]

    operations = [
        # Add features field as object (default={})
        migrations.AddField(
            model_name="servicelevel",
            name="features",
            field=models.JSONField(
                blank=True,
                null=True,
                default=core.field_default({}),
                help_text="Structured features: {first_mile, last_mile, form_factor, b2c, b2b, tracked, ...}",
            ),
        ),
        # Migrate any existing array data to object format
        migrations.RunPython(
            convert_features_array_to_object,
            revert_features_object_to_array,
        ),
    ]
