# Generated by Django 6.0 on 2026-02-19
# Adds pricing_config JSONField to ServiceLevel and RateSheet models
# for markup exclusions (excluded_markup_ids) and service tab ordering (sort_order).

from django.db import migrations, models

import karrio.server.core.models as core


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0101_add_pickup_capability_to_dhl_parcel_de"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelevel",
            name="pricing_config",
            field=models.JSONField(
                blank=True,
                default=core.field_default({}),
                help_text="Pricing config: {excluded_markup_ids: [...], sort_order: 0}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ratesheet",
            name="pricing_config",
            field=models.JSONField(
                blank=True,
                default=core.field_default({}),
                help_text="Pricing config: {excluded_markup_ids: [...]}",
                null=True,
            ),
        ),
    ]
