# Generated by Django 6.0.2 on 2026-02-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0102_add_secret_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='carriersecretref',
            new_name='carrier_sec_carrier_c84a81_idx',
            old_name='carrier_secret_refs_carrier_name_idx',
        ),
        migrations.RenameIndex(
            model_name='secret',
            new_name='secrets_name_6f3326_idx',
            old_name='secrets_name_idx',
        ),
        migrations.RenameIndex(
            model_name='secret',
            new_name='secrets_key_ver_119bc5_idx',
            old_name='secrets_key_version_idx',
        ),
    ]
