# Generated by Django 6.0.2 on 2026-02-25 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0102_add_pricing_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelevel",
            name="carrier_service_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="servicelevel",
            name="service_code",
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[a-z0-9_]+$")]),
        ),
        migrations.AlterField(
            model_name="servicelevel",
            name="service_name",
            field=models.CharField(max_length=100),
        ),
    ]
