# Generated by Django 6.0.3 on 2026-03-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0106_system_rate_sheet'),
    ]

    operations = [
        # Step 3: Alter SystemConnection FK to point to SystemRateSheet
        # (split from 0106 to run in a separate transaction — PostgreSQL
        #  cannot ALTER TABLE while deferred trigger events from the data
        #  migration's DELETE are still pending)
        migrations.AlterField(
            model_name='systemconnection',
            name='rate_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_connections', to='providers.systemratesheet'),
        ),

        # Step 4: Remove is_system field from RateSheet (now AccountRateSheet only)
        migrations.RemoveField(
            model_name='ratesheet',
            name='is_system',
        ),
    ]
