# Generated by Django 6.0.5 on 2026-05-22 08:47

import functools
import karrio.server.core.fields
import karrio.server.core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0112_service_level_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokeredconnection",
            name="capabilities_overrides",
            field=karrio.server.core.fields.MultiChoiceField(
                blank=True,
                choices=[
                    ("pickup", "pickup"),
                    ("rating", "rating"),
                    ("shipping", "shipping"),
                    ("tracking", "tracking"),
                    ("location", "location"),
                    ("paperless", "paperless"),
                    ("manifest", "manifest"),
                    ("duties", "duties"),
                    ("insurance", "insurance"),
                    ("webhook", "webhook"),
                    ("oauth", "oauth"),
                ],
                default=functools.partial(karrio.server.core.models._identity, value=[]),
                help_text="Override capabilities (if empty, uses system capabilities)",
            ),
        ),
        migrations.AlterField(
            model_name="carrierconnection",
            name="capabilities",
            field=karrio.server.core.fields.MultiChoiceField(
                choices=[
                    ("pickup", "pickup"),
                    ("rating", "rating"),
                    ("shipping", "shipping"),
                    ("tracking", "tracking"),
                    ("location", "location"),
                    ("paperless", "paperless"),
                    ("manifest", "manifest"),
                    ("duties", "duties"),
                    ("insurance", "insurance"),
                    ("webhook", "webhook"),
                    ("oauth", "oauth"),
                ],
                default=functools.partial(karrio.server.core.models._identity, value=[]),
                help_text="Enabled carrier capabilities",
            ),
        ),
        migrations.AlterField(
            model_name="systemconnection",
            name="capabilities",
            field=karrio.server.core.fields.MultiChoiceField(
                choices=[
                    ("pickup", "pickup"),
                    ("rating", "rating"),
                    ("shipping", "shipping"),
                    ("tracking", "tracking"),
                    ("location", "location"),
                    ("paperless", "paperless"),
                    ("manifest", "manifest"),
                    ("duties", "duties"),
                    ("insurance", "insurance"),
                    ("webhook", "webhook"),
                    ("oauth", "oauth"),
                ],
                default=functools.partial(karrio.server.core.models._identity, value=[]),
                help_text="Enabled carrier capabilities",
            ),
        ),
    ]
