# Generated by Django 6.0.2 on 2026-02-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("karrio_admin", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="admin_task__queued__be444e_idx",
            old_name="admin_task_e_queued__b1c3e3_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="admin_task__status_3d8254_idx",
            old_name="admin_task_e_status_5a8f2c_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecution",
            new_name="admin_task__task_na_4c0f0d_idx",
            old_name="admin_task_e_task_na_d4e1f7_idx",
        ),
    ]
