# Generated by Django 4.2.11 on 2024-03-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0039_alter_surcharge_carriers"),
        ("pricing", "0049_alter_surcharge_carriers_alter_surcharge_services"),
    ]

    operations = []
