# Generated by Django 5.2.7 on 2025-10-14 01:00

import karrio.server.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0069_alter_surcharge_carriers_alter_surcharge_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surcharge",
            name="carriers",
            field=karrio.server.core.fields.MultiChoiceField(
                blank=True,
                choices=[("generic", "generic")],
                help_text="\n        The list of carriers you want to apply the surcharge to.\n        <br/>\n        Note that by default, the surcharge is applied to all carriers\n        ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surcharge",
            name="services",
            field=karrio.server.core.fields.MultiChoiceField(
                blank=True,
                choices=[],
                help_text="\n        The list of services you want to apply the surcharge to.\n        <br/>\n        Note that by default, the surcharge is applied to all services\n        ",
                null=True,
            ),
        ),
    ]
