# Generated by Django 6.0.2 on 2026-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0080_markup_meta_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markup",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Structured categorization metadata.\n        {\n            "type": "brokerage-fee",       # brokerage-fee | insurance | surcharge | notification | address-validation\n            "plan": "scale",               # Free-form plan/tier name\n            "show_in_preview": true,        # Whether to show computed column in rate sheet preview\n            "feature_gate": "insurance"    # Optional: service feature key that must be supported AND requested in options\n        }\n        ',
            ),
        ),
    ]
