# Generated by Django 3.1.7 on 2021-03-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210308_0302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
