{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "karrio.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karrio.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "karrio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
