apiVersion: v1
kind: Service
metadata:
  name: {{ include "karrio.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karrio.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "karrio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
