# Generated by Django 4.2.8 on 2023-12-21 04:13

from django.db import migrations, models
import django.db.models.fields.json


class Migration(migrations.Migration):
    dependencies = [
        ("tracing", "0004_tracingrecord_carrier_account_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tracingrecord",
            name="request_log_idx",
        ),
        migrations.AddIndex(
            model_name="tracingrecord",
            index=models.Index(
                django.db.models.fields.json.KeyTransform("request_log_id", "meta"),
                condition=models.Q(("meta__request_log_id__isnull", False)),
                name="request_log_idx",
            ),
        ),
    ]
