# Generated by Django 5.2.3 on 2025-06-19 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_appinstallation_app_id_appinstallation_app_type_and_more'),
        ('core', '0004_metafield'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstallation',
            name='api_key',
            field=models.CharField(blank=True, help_text='Auto-generated API key for this app installation', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AppInstallationMetafieldLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metafields_links', to='apps.appinstallation')),
                ('metafield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_installation_link', to='core.metafield')),
            ],
        ),
        migrations.AddField(
            model_name='appinstallation',
            name='metafields',
            field=models.ManyToManyField(related_name='metafield_app_installation', through='apps.AppInstallationMetafieldLink', to='core.metafield'),
        ),
    ]
