# Generated by Django 5.2.5 on 2025-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_appinstallation_api_key_appinstallationmetafieldlink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appinstallation",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated API key for this app installation",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
