# Generated by Django 4.1 on 2022-10-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applink",
            name="item",
        ),
        migrations.RemoveField(
            model_name="applink",
            name="org",
        ),
        migrations.RemoveField(
            model_name="app",
            name="org",
        ),
        migrations.RemoveField(
            model_name="appinstallation",
            name="org",
        ),
        migrations.DeleteModel(
            name="AppInstallationLink",
        ),
        migrations.DeleteModel(
            name="AppLink",
        ),
    ]
