# Generated by Django 5.2.5 on 2025-08-23 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0064_shipment_shipment_created_at_idx_and_more"),
        ("orders", "0016_order_shipments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="order_created_at_idx"),
        ),
    ]
