# Generated by Django 5.2.9 on 2025-12-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_orderkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderkey",
            name="scope",
            field=models.CharField(
                help_text="Organization or user scope id", max_length=50
            ),
        ),
    ]
