# Generated by Django 5.2.10 on 2026-01-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0073_make_shipment_fk_nullable"),
        ("orders", "0021_add_json_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_to",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_order",
                to="manager.address",
            ),
        ),
    ]
