# Generated by Django 5.2.10 on 2026-01-22 14:29

import functools
import karrio.server.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_add_json_indexes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LineItem",
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.JSONField(
                blank=True, help_text="Billing address (embedded JSON)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="line_items",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": []}
                ),
                help_text="Line items array with fulfillment tracking (embedded JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_from",
            field=models.JSONField(
                blank=True,
                help_text="Shipping origin address (embedded JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_to",
            field=models.JSONField(
                blank=True,
                help_text="Shipping destination address (embedded JSON)",
                null=True,
            ),
        ),
    ]
