# Generated by Django 6.0.3 on 2026-04-02 00:57
#
# See modules/manager/karrio/server/manager/migrations/0090_add_archiving_fields.py
# for context. Same rolling-deploy hazard: DDL can partially land while the
# django_migrations row is never recorded, leaving subsequent `migrate` runs
# stuck on DuplicateColumn. The DB operations are guarded via introspection;
# state operations are preserved so downstream migrations build correct state.

from django.db import migrations, models


def _archived_at_field():
    field = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Timestamp when the record was archived. Null if not archived.",
    )
    field.set_attributes_from_name("archived_at")
    return field


def _is_archived_field():
    field = models.BooleanField(
        db_index=True,
        default=False,
        help_text="Archived records are excluded from default queries.",
    )
    field.set_attributes_from_name("is_archived")
    return field


def _existing_columns(schema_editor, model):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, model._meta.db_table)
        }


def forwards(apps, schema_editor):
    model = apps.get_model("orders", "order")
    existing = _existing_columns(schema_editor, model)
    if "archived_at" not in existing:
        schema_editor.add_field(model, _archived_at_field())
    if "is_archived" not in existing:
        schema_editor.add_field(model, _is_archived_field())


def backwards(apps, schema_editor):
    model = apps.get_model("orders", "order")
    existing = _existing_columns(schema_editor, model)
    for column_name in ("is_archived", "archived_at"):
        if column_name in existing:
            schema_editor.remove_field(model, model._meta.get_field(column_name))


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0025_cleanup"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="order",
                    name="archived_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was archived. Null if not archived.",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="order",
                    name="is_archived",
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Archived records are excluded from default queries.",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards, backwards),
            ],
        ),
    ]
