# Generated by Django 6.0.3 on 2026-04-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the record was archived. Null if not archived.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Archived records are excluded from default queries.",
            ),
        ),
    ]
