# Generated by Django 3.2.3 on 2021-05-18 10:53

from django.db import migrations
import karrio.server.core.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_tracking', '0011_auto_20201117_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
            ],
            options={
                'ordering': ['-requested_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest_framework_tracking.apirequestlog', karrio.server.core.models.base.ControlledAccessModel),
        ),
    ]
