# Generated by Django 4.2.8 on 2024-01-13 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import karrio.server.core.models.base


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_apilogindex_test_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metafield",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            karrio.server.core.models.base.uuid,
                            *(),
                            **{"prefix": "metaf_"}
                        ),
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(db_index=True, max_length=50, verbose_name="name"),
                ),
                ("value", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("number", "number"),
                            ("boolean", "boolean"),
                        ],
                        db_index=True,
                        default="text",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Metafield",
                "verbose_name_plural": "Metafields",
                "db_table": "metafield",
            },
            bases=(karrio.server.core.models.base.ControlledAccessModel, models.Model),
        ),
    ]
