# Generated by Django 5.2.10 on 2026-01-27 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0006_add_api_log_requested_at_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metafield",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The type of object this metafield is attached to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="metafield",
            name="object_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The ID of the object this metafield is attached to",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="metafield",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="metafield_content_8a0d28_idx",
            ),
        ),
    ]
