# Generated by Django 3.2.5 on 2021-08-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_auto_20210805_0359'),
        ('orgs', '0002_organization_surcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='system_carriers',
            field=models.ManyToManyField(related_name='active_orgs', to='providers.Carrier'),
        ),
    ]
