# Generated by Django 3.2.13 on 2022-07-10 13:07

from django.db import migrations, models
import django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_custom_migration_2022_4'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(django.db.models.fields.json.KeyTextTransform('id', 'data'), condition=models.Q(('data__id__isnull', False)), name='event_object_idx'),
        ),
    ]
