# Generated by Django 3.2.8 on 2021-10-13 15:20

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_alter_surcharge_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surcharge',
            name='discount_range',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, help_text='\n        Add the surcharge, if the rate discount is within this discount rate range.\n        <br/>\n        By default, the surcharge is applied to all quotes no matter the discount amount.\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='freight_range',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, help_text='\n        Add the surcharge, if the rate charge is within this freight (quote) price range.\n        <br/>\n        By default, the surcharge is applied to all quotes no matter the amount.\n        ', null=True),
        ),
    ]
