# Generated by Django 4.1.6 on 2023-02-04 09:48

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0027_alter_surcharge_services"),
    ]

    operations = []

    if "postgres" in settings.DB_ENGINE:
        operations = [
            migrations.RunSQL('ALTER TABLE "surcharge" ALTER COLUMN "carriers" TYPE jsonb USING to_jsonb(carriers)'),
            migrations.RunSQL('ALTER TABLE "surcharge" ALTER COLUMN "services" TYPE jsonb USING to_jsonb(services)'),
        ]

