# Generated by Django 5.0 on 2023-12-08 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="label",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="label"
            ),
            preserve_default=False,
        ),
    ]
