# Generated by Django 3.1.7 on 2021-03-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import karrio.server.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0009_auto_20210326_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=karrio.server.core.models.uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customs', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.customs')),
                ('parcel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.parcel')),
            ],
            options={
                'db_table': 'template',
                'ordering': ['-created_at'],
            },
        ),
    ]
