# Generated by Django 3.2.9 on 2021-11-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
        ('orgs', '0003_organization_system_carriers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='events.event')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='events',
            field=models.ManyToManyField(related_name='org', through='orgs.EventLink', to='events.Event'),
        ),
    ]
