# Generated by Django 3.2.14 on 2022-08-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_documentuploadrecord'),
        ('orgs', '0007_auto_20220628_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecordLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='manager.documentuploadrecord')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_record_links', to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='upload_records',
            field=models.ManyToManyField(related_name='org', through='orgs.UploadRecordLink', to='manager.DocumentUploadRecord'),
        ),
    ]
