# Generated by Django 5.2.7 on 2025-10-03 00:13

import django.db.models.deletion
import functools
import karrio.server.core.models
import karrio.server.core.models.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0021_remove_organization_installations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=functools.partial(karrio.server.core.models.base.uuid, *(), **{'prefix': 'mtd_'}), editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.CharField(db_index=True, max_length=150, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('carrier_code', models.CharField(max_length=100, verbose_name='carrier_code')),
                ('carrier_service', models.CharField(max_length=150, verbose_name='carrier_service')),
                ('carrier_ids', models.JSONField(blank=True, default=functools.partial(karrio.server.core.models._identity, *(), **{'value': []}), null=True)),
                ('carrier_options', models.JSONField(blank=True, default=functools.partial(karrio.server.core.models._identity, *(), **{'value': {}}), null=True)),
                ('metadata', models.JSONField(blank=True, default=functools.partial(karrio.server.core.models._identity, *(), **{'value': {}}), null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'db_table': 'shipping-methods',
                'ordering': ['-created_at'],
            },
            bases=(karrio.server.core.models.base.ControlledAccessModel, models.Model),
        ),
        migrations.CreateModel(
            name='ShippingMethodLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='shipping.shippingmethod')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_method_links', to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='org',
            field=models.ManyToManyField(related_name='shipping_methods', through='shipping.ShippingMethodLink', to='orgs.organization'),
        ),
    ]
