# Generated by Django 5.2.7 on 2025-10-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='carrier_ids',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='carrier_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='carrier_id'),
        ),
    ]
