#!/bin/bash

# Setup environment variables
export DASHBOARD_PORT=${DASHBOARD_PORT:=3002}
export AUTH_TRUST_HOST=${AUTH_TRUST_HOST:=true}
export NEXTAUTH_URL=${NEXTAUTH_URL:=$NEXT_PUBLIC_DASHBOARD_URL}
export NEXTAUTH_SECRET=${NEXTAUTH_SECRET:="0/zfUEetNIle3iNekk4npo4T1pLFAWOyBFgbAu0afB4="}
export NEXT_PUBLIC_KARRIO_PUBLIC_URL=${NEXT_PUBLIC_KARRIO_PUBLIC_URL:="http://localhost:5002"}

# Start services
set -e

echo "Starting dashboard..."
echo "NEXTAUTH_URL: $NEXTAUTH_URL"
echo "KARRIO_URL: $KARRIO_URL"
echo "KARRIO_PUBLIC_URL: $NEXT_PUBLIC_KARRIO_PUBLIC_URL"
echo "DASHBOARD_PORT: $DASHBOARD_PORT"

export PORT=$DASHBOARD_PORT
export HOSTNAME="0.0.0.0"
node apps/dashboard/server.js &

wait -n
