# Generated by Django 3.2.4 on 2021-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20210603_2149'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='surcharges',
            field=models.ManyToManyField(related_name='org', to='pricing.Surcharge'),
        ),
    ]
