# Generated by Django 3.0.4 on 2020-03-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FedexSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('meter_number', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='CanadaPostSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('customer_number', models.CharField(max_length=200)),
                ('contract_id', models.CharField(max_length=200)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrier')),
            ],
        ),
    ]
