# Generated by Django 3.0.4 on 2020-03-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='test',
            field=models.BooleanField(),
        ),
    ]
