# Generated by Django 3.2.9 on 2021-11-09 13:33

from django.db import migrations, models
import functools
import karrio.server.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20210722_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='messages',
            field=models.JSONField(blank=True, default=functools.partial(karrio.server.core.utils.identity, *(), **{'value': []}), null=True),
        ),
    ]
