# Generated by Django 3.2.9 on 2021-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_tracking_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
