# Generated by Django 4.2.8 on 2023-12-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0053_alter_commodity_weight_unit_alter_parcel_weight_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="company_name",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="person_name",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
