# Generated by Django 5.2.5 on 2025-08-23 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0063_alter_commodity_value_currency"),
        ("providers", "0084_alter_servicelevel_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["created_at"], name="shipment_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="tracking",
            index=models.Index(fields=["created_at"], name="tracking_created_at_idx"),
        ),
    ]
