# Generated by Django 4.2.8 on 2023-12-27 20:08

from django.db import migrations, transaction


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Workflow = apps.get_model("automation", "Workflow")
    WorkflowAction = apps.get_model("automation", "WorkflowAction")
    WorkflowTrigger = apps.get_model("automation", "WorkflowTrigger")
    WorkflowConnection = apps.get_model("automation", "WorkflowConnection")

    with transaction.atomic():
        # -----------------------------------------------------------
        # Create workflow connection templates
        # -----------------------------------------------------------
        # region

        _connection_templates = [
            {
                "is_public": True,
                "name": "Shopify Access Token Connection",
                "slug": "$.shopify-access-token.workflow.connection",
                "auth_type": "api_key",
                "auth_template": '{ "X-Shopify-Access-Token": "{{credentials.access_token}}" }',
            },
            {
                "is_public": True,
                "name": "Karrio Token Connection",
                "slug": "$.karrio-token.workflow.connection",
                "auth_type": "api_key",
                "auth_template": '{ "Authorization": "Token {{credentials.token}}" }',
            },
        ]
        _existing_connections = WorkflowConnection.objects.using(db_alias).filter(
            slug__in=[_.get("slug") for _ in _connection_templates]
        )
        WorkflowConnection.objects.using(db_alias).bulk_create(
            [
                WorkflowConnection(**_)
                for _ in _connection_templates
                if not _existing_connections.filter(slug=_.get("slug")).exists()
            ]
        )

        # endregion

        # -----------------------------------------------------------
        # Create workflow action templates
        # -----------------------------------------------------------
        # region

        _action_templates = [
            {
                "is_public": True,
                "name": "Shopify Orders",
                "action_type": "http_request",
                "slug": "$.shopify-orders.workflow.action",
                "host": "https://myshop.myshopify.com",
                "endpoint": "/admin/api/2023-04/orders.json",
                "method": "get",
                "header_template": '{"X-Shopify-Access-Token": "{{connection[\'X-Shopify-Access-Token\']}}"}',
                "parameters_type": "queystring",
                "parameters_template": '{"status": "open" }',
                "content_type": "json",
                "connection": WorkflowConnection.objects.using(db_alias).get(
                    slug="$.shopify-access-token.workflow.connection"
                ),
            },
            {
                "is_public": True,
                "name": "Karrio bacth orders creation",
                "action_type": "http_request",
                "slug": "$.create-batch-orders.workflow.action",
                "host": "https://api.karrio.io",
                "endpoint": "/v1/batches/orders",
                "method": "post",
                "header_template": '{"Authorization": "Token {{connection[\'Authorization\']}}"}',
                "parameters_type": "data",
                "parameters_template": """{
                        "orders": [
                            {% set response = lib.to_dict(parameters.results[0].response) %}
                            {% for order in response.orders %}
                            {% set customer = order.customer %}
                            {% set shipping_address = order.shipping_address or (customer.default_address if customer else None) %}
                            {% if shipping_address.address1 %}
                            {
                            "order_id": "{{order.order_number}}",
                            "order_date": "{{lib.fdate(order.created_at, '%Y-%m-%dT%H:%M:%S%z')}}",
                            "source": "Shopify",
                            "shipping_to": {
                                "postal_code": "{{shipping_address.zip}}",
                                "city": "{{shipping_address.city}}",
                                "person_name": "{{shipping_address.name}}",
                                "company_name": "{{shipping_address.company}}",
                                "country_code": "{{shipping_address.country_code}}",
                                {% if customer %}
                                "email": "{{customer.email}}",
                                {% endif %}
                                "phone_number": "{{shipping_address.phone}}",
                                "state_code": "{{shipping_address.province_code}}",
                                "residential": {{shipping_address.company == null}},
                                "address_line1": "{{shipping_address.address1}}",
                                "address_line2": "{{shipping_address.address2}}",
                            },
                            {% if order.billing_address %}
                            "billing_address": {
                                "postal_code": "{{order.billing_address.zip}}",
                                "city": "{{order.billing_address.city}}",
                                "person_name": "{{order.billing_address.name}}",
                                "company_name": "{{order.billing_address.company}}",
                                "country_code": "{{order.billing_address.country_code}}",
                                "email": null,
                                "phone_number": "{{order.billing_address.phone}}",
                                "state_code": "{{order.billing_address.province_code}}",
                                "residential": {{order.billing_address.company == null}},
                                "address_line1": "{{order.billing_address.address1}}",
                                "address_line2": "{{order.billing_address.address2}}",
                            },
                            {% endif %}
                            "line_items": [
                                {% for item in order.line_items %}
                                {
                                "weight": {{lib.units.Weight(item.grams, "G").KG}},
                                "weight_unit": "KG",
                                "title": "{{item.title}}",
                                "description": "{{item.name}}",
                                "quantity": {{item.quantity}},
                                "sku": "{{item.sku}}",
                                "hs_code": "{{item.code}}",
                                "value_amount": {{lib.to_money(item.price)}},
                                "value_currency": "{{item.price_set.shop_money.currency_code}}",
                                {% if item.origin_location %}
                                "origin_country": "{{item.origin_location.country_code}}",
                                {% endif %}
                                }
                                {% endfor %}
                            ],
                            "metadata": {
                                "shopify_order_id": "{{order.id}}",
                            }
                            }
                            {% endif %}
                            {% endfor %}
                        ]
                        }
                        """,
                "content_type": "json",
                "connection": WorkflowConnection.objects.using(db_alias).get(
                    slug="$.karrio-token.workflow.connection"
                ),
            },
        ]
        _existing_actions = WorkflowAction.objects.using(db_alias).filter(
            slug__in=[_.get("slug") for _ in _action_templates]
        )
        WorkflowAction.objects.using(db_alias).bulk_create(
            [
                WorkflowAction(**_)
                for _ in _action_templates
                if not _existing_actions.filter(slug=_.get("slug")).exists()
            ]
        )

        # endregion
        # -----------------------------------------------------------
        # Create workflow templates
        # -----------------------------------------------------------
        # region

        _workflow_templates = [
            {
                "is_public": True,
                "name": "Shopify order sync",
                "slug": "$.shopify-order-sync.workflow",
                "action_nodes": [
                    {"slug": "$.shopify-orders.workflow.action", "order": 0},
                    {"slug": "$.create-batch-orders.workflow.action", "order": 1},
                ],
            }
        ]
        _existing_workflows = Workflow.objects.using(db_alias).filter(
            slug__in=[_.get("slug") for _ in _workflow_templates]
        )
        Workflow.objects.using(db_alias).bulk_create(
            [
                Workflow(**_)
                for _ in _workflow_templates
                if not _existing_workflows.filter(slug=_.get("slug")).exists()
            ]
        )

        # endregion

        # -----------------------------------------------------------
        # Create workflow trigger templates
        # -----------------------------------------------------------
        # region

        _trigger_templates = [
            {
                "trigger_type": "webhook",
                "slug": "$.shopify-order-webhook.workflow.trigger",
                "workflow": Workflow.objects.using(db_alias).get(
                    slug="$.shopify-order-sync.workflow"
                ),
            },
        ]
        _existing_triggers = WorkflowTrigger.objects.using(db_alias).filter(
            slug__in=[_.get("slug") for _ in _trigger_templates]
        )
        WorkflowTrigger.objects.using(db_alias).bulk_create(
            [
                WorkflowTrigger(**_)
                for _ in _trigger_templates
                if not _existing_triggers.filter(slug=_.get("slug")).exists()
            ]
        )

        # endregion


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
