# Generated by Django 3.2.4 on 2021-06-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20210601_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
