import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { Clock, Edit, MoreVertical, Package, Plus, Search, Trash2, Truck } from 'lucide-react'
import { toast } from 'sonner'
import { Shell } from '@/components/layouts/shell'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { CarrierImage } from '@/components/ui/carrier-image'
import { StatusBadge } from '@/components/ui/status-badge'
import { ConfirmationDialog } from '@/components/ui/confirmation-dialog'
import { Switch } from '@/components/ui/switch'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { ShippingMethodDialog } from '@/components/shipping-method-dialog'
import type { ShippingMethod } from '@/types/shipping-methods'
import {
  useShippingMethods,
  useCreateShippingMethod,
  useUpdateShippingMethod,
  useDeleteShippingMethod,
} from '@/hooks/useShippingMethods'

export const Route = createFileRoute('/shipping-methods')({
  component: ShippingMethodsPage,
  head: () => ({
    meta: [{ title: 'Shipping Methods - JTL Shipping' }],
  }),
})

type FilterType = 'all' | 'active' | 'inactive'

function ShippingMethodsPage() {
  const [searchTerm, setSearchTerm] = useState('')
  const [filter, setFilter] = useState<FilterType>('all')
  const [dialogOpen, setDialogOpen] = useState(false)
  const [selectedMethod, setSelectedMethod] = useState<ShippingMethod | null>(null)
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false)
  const [methodToDelete, setMethodToDelete] = useState<string | null>(null)

  // Fetch shipping methods
  const { data, isLoading, error, refetch } = useShippingMethods()
  const methods = data?.shipping_methods || []

  // Mutations
  const createMethod = useCreateShippingMethod()
  const updateMethod = useUpdateShippingMethod()
  const deleteMethod = useDeleteShippingMethod()

  const handleToggleMethod = async (method: ShippingMethod) => {
    try {
      await updateMethod.mutateAsync({
        id: method.id,
        is_active: !method.is_active,
      })
      toast.success(
        `Shipping method ${method.is_active ? 'deactivated' : 'activated'} successfully`
      )
    } catch (error: any) {
      toast.error(error?.message || 'Failed to toggle shipping method')
    }
  }

  const handleDeleteMethod = async (id: string) => {
    try {
      await deleteMethod.mutateAsync(id)
      toast.success('Shipping method deleted successfully')
      setDeleteDialogOpen(false)
      setMethodToDelete(null)
    } catch (error: any) {
      toast.error(error?.message || 'Failed to delete shipping method')
    }
  }

  const handleAddMethod = () => {
    setSelectedMethod(null)
    setDialogOpen(true)
  }

  const handleEditMethod = (method: ShippingMethod) => {
    setSelectedMethod(method)
    setDialogOpen(true)
  }

  const handleDialogSubmit = async (values: any, method: ShippingMethod | null) => {
    try {
      if (method) {
        await updateMethod.mutateAsync({
          id: method.id,
          ...values,
        })
        toast.success('Shipping method updated successfully')
      } else {
        // For create, exclude slug as it's auto-generated by the API
        const { slug, ...createData } = values
        await createMethod.mutateAsync(createData)
        toast.success('Shipping method created successfully')
      }
      await refetch()
    } catch (error: any) {
      throw error
    }
  }

  const handleDialogSuccess = () => {
    setDialogOpen(false)
    setSelectedMethod(null)
  }

  const filterMethods = (methods: ShippingMethod[]) => {
    let filtered = methods

    // Apply status filter
    if (filter === 'active') {
      filtered = filtered.filter((m) => m.is_active)
    } else if (filter === 'inactive') {
      filtered = filtered.filter((m) => !m.is_active)
    }

    // Apply search filter
    if (searchTerm) {
      filtered = filtered.filter(
        (method) =>
          method.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
          method.carrier_code?.toLowerCase().includes(searchTerm.toLowerCase()) ||
          method.carrier_service?.toLowerCase().includes(searchTerm.toLowerCase())
      )
    }

    return filtered
  }

  const filteredMethods = filterMethods(methods)

  const renderMethodCard = (method: ShippingMethod) => {
    return (
      <Card
        key={method.id}
        className={`relative group hover:shadow-lg transition-shadow duration-200 border-l-4 ${
          method.is_active
            ? 'border-l-green-500'
            : 'border-l-gray-300 dark:border-l-gray-700'
        }`}
      >
        <CardContent className="p-6">
          {/* Header with carrier info and status */}
          <div className="flex items-start justify-between mb-6">
            <div className="flex items-start gap-4 flex-1">
              <div className="relative">
                <CarrierImage
                  carrierName={method.carrier_code}
                  size="lg"
                  fallbackBackground={method.is_active ? '#16a34a' : '#6b7280'}
                  className="rounded-xl shadow-sm"
                />
                {/* Status indicator */}
                <div
                  className={`absolute -top-1 -right-1 w-4 h-4 rounded-full border-2 border-background ${
                    method.is_active ? 'bg-green-500 dark:bg-green-400' : 'bg-muted'
                  }`}
                />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between mb-2">
                  <h3 className="font-semibold text-lg text-foreground truncate">
                    {method.name}
                  </h3>
                </div>
                <p className="text-sm text-muted-foreground mb-2 font-medium">
                  {method.carrier_code} • {method.carrier_service}
                </p>
                <div className="flex items-center gap-2 text-sm flex-wrap">
                  <StatusBadge status={method.is_active ? 'active' : 'inactive'} />
                  {method.test_mode && <StatusBadge status="test" />}
                </div>
              </div>
            </div>

            {/* Actions dropdown */}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                  <MoreVertical className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={() => handleEditMethod(method)}>
                  <Edit className="h-4 w-4 mr-2" />
                  Edit
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem
                  variant="destructive"
                  onClick={() => {
                    setMethodToDelete(method.id)
                    setDeleteDialogOpen(true)
                  }}
                >
                  <Trash2 className="h-4 w-4 mr-2" />
                  Delete
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          {/* Method details */}
          {method.description && (
            <p className="text-sm text-muted-foreground mb-4">{method.description}</p>
          )}

          <div className="flex flex-col gap-3 mb-4">
            <div className="flex items-center justify-between p-3 bg-card rounded-lg border">
              <span className="text-sm font-medium text-muted-foreground">Service</span>
              <span className="font-semibold text-foreground text-sm">
                {method.carrier_service}
              </span>
            </div>
            <div className="flex items-center justify-between p-3 bg-card rounded-lg border">
              <span className="text-sm font-medium text-muted-foreground">Status</span>
              <Switch
                checked={method.is_active}
                onCheckedChange={() => handleToggleMethod(method)}
                disabled={updateMethod.isPending}
              />
            </div>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Shell
      currentPage="shipping-methods"
      pageTitle="Shipping Methods"
      pageDescription="Configure and manage shipping methods for your store"
    >
      {/* Header Actions */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4 flex-1">
          {/* Search */}
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              type="search"
              placeholder="Search methods by name, carrier, or service..."
              className="pl-8"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          {/* Filter */}
          <Select
            value={filter}
            onValueChange={(value: FilterType) => setFilter(value)}
          >
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Filter by status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Methods</SelectItem>
              <SelectItem value="active">Active Only</SelectItem>
              <SelectItem value="inactive">Inactive Only</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <Button onClick={handleAddMethod}>
          <Plus className="h-4 w-4 mr-2" />
          Add Method
        </Button>
      </div>

      {/* Error State */}
      {error && (
        <Alert variant="destructive" className="mb-6">
          <AlertDescription>
            Failed to load shipping methods. Please try again.
          </AlertDescription>
        </Alert>
      )}

      {/* Loading State */}
      {isLoading && (
        <div className="text-center py-12">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary mb-4" />
          <div className="text-lg">Loading shipping methods...</div>
        </div>
      )}

      {/* Shipping Methods Grid */}
      {!isLoading && (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {filteredMethods.map((method) => renderMethodCard(method))}
        </div>
      )}

      {/* Empty State */}
      {!isLoading && filteredMethods.length === 0 && (
        <div className="text-center py-16">
          <div className="bg-primary/10 rounded-full w-24 h-24 flex items-center justify-center mx-auto mb-6">
            <Truck className="h-12 w-12 text-primary" />
          </div>
          <h3 className="text-xl font-semibold mb-3 text-foreground">
            {searchTerm || filter !== 'all'
              ? 'No methods found'
              : 'No shipping methods configured'}
          </h3>
          <p className="text-muted-foreground mb-6 max-w-md mx-auto">
            {searchTerm || filter !== 'all'
              ? 'No methods match your search or filter criteria. Try adjusting your search terms.'
              : 'Get started by creating your first shipping method to offer shipping options to your customers.'}
          </p>
          <Button className="px-6 py-2" onClick={handleAddMethod}>
            <Plus className="h-4 w-4 mr-2" />
            Create First Method
          </Button>
        </div>
      )}

      {/* Shipping Method Dialog */}
      <ShippingMethodDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        selectedMethod={selectedMethod}
        onSubmit={handleDialogSubmit}
        onSuccess={handleDialogSuccess}
      />

      {/* Delete Confirmation Dialog */}
      <ConfirmationDialog
        open={deleteDialogOpen}
        onOpenChange={setDeleteDialogOpen}
        title="Delete Shipping Method"
        description="Are you sure you want to delete this shipping method? This action cannot be undone and may affect existing shipments."
        confirmLabel="Delete"
        cancelLabel="Cancel"
        onConfirm={() => methodToDelete && handleDeleteMethod(methodToDelete)}
        isLoading={deleteMethod.isPending}
      />
    </Shell>
  )
}
