# Generated by Django 3.2.13 on 2022-07-06 13:50

from django.db import migrations, models
import functools
import karrio.server.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='test_mode',
            field=models.BooleanField(default=functools.partial(karrio.server.core.models._identity, *(), **{'value': False})),
        ),
    ]
