# Generated by Django 3.1.3 on 2020-11-27 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commodity', 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='customs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customs Info', 'verbose_name_plural': 'Customs Info'},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Parcel', 'verbose_name_plural': 'Parcels'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='pickup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pickup', 'verbose_name_plural': 'Pickups'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tracking Satus', 'verbose_name_plural': 'Tracking Statuses'},
        ),
        migrations.AddField(
            model_name='commodity',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('LB', 'LB')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.customs'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.payment'),
        ),
    ]
