# Generated by Django 4.1.7 on 2023-02-22 15:35

from django.db import migrations, models
import functools
import karrio.server.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_alter_batchoperation_resource_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatemplate",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.models._identity, *(), **{"value": {}}
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="batchoperation",
            name="resources",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.models._identity, *(), **{"value": []}
                ),
                null=True,
            ),
        ),
    ]
