# Generated by Django 3.2.14 on 2022-08-30 10:45

from django.db import migrations, models
import functools
import karrio.server.core.fields
import karrio.server.core.models
import karrio.server.conf as conf


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Client = apps.get_model("tenants", "Client")
    clients = []

    for client in Client.objects.using(db_alias).all():
        client.features = {
            flag: flag in client.feature_flags
            for flag, _ in conf.settings.FEATURE_FLAGS
        }
        clients.append(client)

    if any(clients):
        Client.objects.using(db_alias).bulk_update(clients, fields=["features"])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_client_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='features',
            field=models.JSONField(blank=True, default=functools.partial(karrio.server.core.models._identity, *(), **{'value': {}}), help_text='The feature flags.', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='feature_flags',
            field=karrio.server.core.fields.MultiChoiceField(base_field=models.CharField(choices=[('AUDIT_LOGGING', 'AUDIT_LOGGING'), ('ALLOW_SIGNUP', 'ALLOW_SIGNUP'), ('ALLOW_ADMIN_APPROVED_SIGNUP', 'ALLOW_ADMIN_APPROVED_SIGNUP'), ('ALLOW_MULTI_ACCOUNT', 'ALLOW_MULTI_ACCOUNT'), ('ORDERS_MANAGEMENT', 'ORDERS_MANAGEMENT'), ('APPS_MANAGEMENT', 'APPS_MANAGEMENT'), ('DOCUMENTS_MANAGEMENT', 'DOCUMENTS_MANAGEMENT'), ('DATA_IMPORT_EXPORT', 'DATA_IMPORT_EXPORT'), ('CUSTOM_CARRIER_DEFINITION', 'CUSTOM_CARRIER_DEFINITION'), ('PERSIST_SDK_TRACING', 'PERSIST_SDK_TRACING'), ('ORG_LEVEL_BILLING', 'ORG_LEVEL_BILLING'), ('TENANT_LEVEL_BILLING', 'TENANT_LEVEL_BILLING')], max_length=100), default=functools.partial(karrio.server.core.models._identity, *(), **{'value': {'ALLOW_ADMIN_APPROVED_SIGNUP': False, 'ALLOW_MULTI_ACCOUNT': True, 'ALLOW_SIGNUP': True, 'APPS_MANAGEMENT': True, 'AUDIT_LOGGING': True, 'CUSTOM_CARRIER_DEFINITION': True, 'DATA_IMPORT_EXPORT': True, 'DOCUMENTS_MANAGEMENT': True, 'ORDERS_MANAGEMENT': True, 'ORG_LEVEL_BILLING': True, 'PERSIST_SDK_TRACING': True, 'TENANT_LEVEL_BILLING': False}}), help_text='The list of feature flags.', size=None),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
