# Generated by Django 3.2.14 on 2022-08-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_auto_20220830_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='feature_flags',
        ),
    ]
