# Generated by Django 3.1.5 on 2021-01-25 04:48

from django.db import migrations, models
import purpleserver.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20201231_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingcharge',
            name='carriers',
            field=purpleserver.core.fields.MultiChoiceField(base_field=models.CharField(choices=[('canadapost', 'canadapost'), ('dhl_express', 'dhl_express'), ('fedex_express', 'fedex_express'), ('purolator_courier', 'purolator_courier'), ('ups_package', 'ups_package'), ('freightcom', 'freightcom'), ('eshipper', 'eshipper')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
