import unittest
from unittest.mock import patch, ANY
from .fixture import gateway
from tests import logger

import karrio
import karrio.lib as lib
import karrio.core.models as models


class TestEasyshipRating(unittest.TestCase):
    def setUp(self):
        self.maxDiff = None
        self.RateRequest = models.RateRequest(**RatePayload)

    def test_create_rate_request(self):
        request = gateway.mapper.create_rate_request(self.RateRequest)

        self.assertEqual(request.serialize(), RateRequest)

    def test_get_rate(self):
        with patch("karrio.mappers.easyship.proxy.lib.request") as mock:
            mock.return_value = "{}"
            karrio.Rating.fetch(self.RateRequest).from_(gateway)

            self.assertEqual(
                mock.call_args[1]["url"],
                f"{gateway.settings.server_url}/2023-01/rates",
            )

    def test_parse_rate_response(self):
        with patch("karrio.mappers.easyship.proxy.lib.request") as mock:
            mock.return_value = RateResponse
            parsed_response = (
                karrio.Rating.fetch(self.RateRequest).from_(gateway).parse()
            )
            self.assertListEqual(lib.to_dict(parsed_response), ParsedRateResponse)


if __name__ == "__main__":
    unittest.main()


RatePayload = {
    "shipper": {
        "company_name": None,
        "address_line1": "Kennedy Town",
        "address_line2": "Block 3",
        "city": "Hong Kong",
        "postal_code": "0000",
        "country_code": "HK",
        "person_name": "Foo Bar",
        "state_code": "Yuen Long",
        "email": "asd@asd.com",
        "phone_number": None,
    },
    "recipient": {
        "company_name": None,
        "address_line1": "Kennedy Town",
        "address_line2": "Block 3",
        "city": "Hong Kong",
        "postal_code": "0000",
        "country_code": "HK",
        "person_name": "Foo Bar",
        "state_code": "Yuen Long",
        "email": "asd@asd.com",
        "phone_number": None,
    },
    "parcels": [
        {
            "height": 3,
            "length": 1,
            "width": 2,
            "weight": 1,
            "weight_unit": "KG",
            "dimension_unit": "CM",
            "items": [
                {
                    "sku": "sku",
                    "quantity": 2,
                    "weight": 10,
                    "weight_unit": "KG",
                    "origin_country": "HK",
                    "value_amount": 20,
                    "value_currency": "USD",
                    "description": "item",
                    "category": "fashion",
                    "metadata": {
                        "contains_battery_pi966": True,
                        "contains_battery_pi967": True,
                        "contains_liquids": True,
                    },
                }
            ],
        }
    ],
    "options": {
        "easyship_apply_shipping_rules": True,
        "easyship_show_courier_logo_url": False,
        "easyship_incoterms": "DDU",
    },
}

ParsedRateResponse = [
    [
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 34.96, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 5.59, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff"],
                "cost_rank": 2,
                "delivery_time_rank": 6,
                "easyship_courier_id": "4cf66d63-4e4a-456b-86c1-50964ad9f7b7",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 3,
                "min_delivery_time": 1,
                "rate_provider": "fedex",
                "service_name": "easyship_fedex_ground",
                "tracking_rating": 3,
                "value_for_money_rank": 1,
            },
            "service": "easyship_fedex_ground",
            "total_charge": 40.55,
            "transit_days": 3,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 76.2, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 0.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff", "free_pickup"],
                "cost_rank": 5,
                "delivery_time_rank": 8,
                "easyship_courier_id": "7505df80-af51-46a0-b2ee-ac9eacfcd3e4",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 3,
                "min_delivery_time": 1,
                "rate_provider": "usps",
                "service_name": "easyship_usps_priority_mail",
                "tracking_rating": 2,
                "value_for_money_rank": 2,
            },
            "service": "easyship_usps_priority_mail",
            "total_charge": 76.2,
            "transit_days": 3,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 79.9, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 0.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff", "free_pickup"],
                "cost_rank": 6,
                "delivery_time_rank": 7,
                "easyship_courier_id": "137a79e8-ae1c-4369-9855-44cf8ff784c4",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 3,
                "min_delivery_time": 1,
                "rate_provider": "usps",
                "service_name": "easyship_usps_priority_mail_signature",
                "tracking_rating": 2,
                "value_for_money_rank": 3,
            },
            "service": "easyship_usps_priority_mail_signature",
            "total_charge": 79.9,
            "transit_days": 3,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 26.29, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 0.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff"],
                "cost_rank": 1,
                "delivery_time_rank": 10,
                "easyship_courier_id": "eac604a4-34c9-41b6-b5b1-231fb785d071",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 5,
                "min_delivery_time": 2,
                "rate_provider": "fedex",
                "service_name": "easyship_fedex_smart_post",
                "tracking_rating": 3,
                "value_for_money_rank": 4,
            },
            "service": "easyship_fedex_smart_post",
            "total_charge": 26.29,
            "transit_days": 5,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 48.56, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 0.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff", "free_pickup"],
                "cost_rank": 3,
                "delivery_time_rank": 12,
                "easyship_courier_id": "c3e97b11-2842-44f1-84d1-afaa6b3f0a7c",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 5,
                "min_delivery_time": 2,
                "rate_provider": "usps",
                "service_name": "easyship_usps_ground_advantage",
                "tracking_rating": 2,
                "value_for_money_rank": 5,
            },
            "service": "easyship_usps_ground_advantage",
            "total_charge": 48.56,
            "transit_days": 5,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 52.26, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 0.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff", "free_pickup"],
                "cost_rank": 4,
                "delivery_time_rank": 11,
                "easyship_courier_id": "7a1424ff-0d4e-4d55-bdfe-e4c6661debbf",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 5,
                "min_delivery_time": 2,
                "rate_provider": "usps",
                "service_name": "easyship_usps_ground_advantage",
                "tracking_rating": 2,
                "value_for_money_rank": 6,
            },
            "service": "easyship_usps_ground_advantage",
            "total_charge": 52.26,
            "transit_days": 5,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 91.69, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 0.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff"],
                "cost_rank": 7,
                "delivery_time_rank": 5,
                "easyship_courier_id": "84135827-1538-4be2-b26e-afd8b3f3b4bd",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 2,
                "min_delivery_time": 2,
                "rate_provider": "fedex",
                "service_name": "easyship_fedex_2_day",
                "tracking_rating": 3,
                "value_for_money_rank": 7,
            },
            "service": "easyship_fedex_2_day",
            "total_charge": 91.69,
            "transit_days": 2,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 180.55, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 0.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff", "free_pickup"],
                "cost_rank": 9,
                "delivery_time_rank": 3,
                "easyship_courier_id": "a623a62b-5631-4dce-ae15-bbcf89e49c52",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 2,
                "min_delivery_time": 1,
                "rate_provider": "usps",
                "service_name": "easyship_usps_priority_mail_express",
                "tracking_rating": 2,
                "value_for_money_rank": 8,
            },
            "service": "easyship_usps_priority_mail_express",
            "total_charge": 180.55,
            "transit_days": 2,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 120.64, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 19.0, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff"],
                "cost_rank": 8,
                "delivery_time_rank": 9,
                "easyship_courier_id": "a9e3f424-713c-4efa-b445-71cd60c88ccd",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 3,
                "min_delivery_time": 2,
                "rate_provider": "fedex",
                "service_name": "easyship_fedex_express_saver",
                "tracking_rating": 3,
                "value_for_money_rank": 9,
            },
            "service": "easyship_fedex_express_saver",
            "total_charge": 139.64,
            "transit_days": 3,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 202.79, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 31.94, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff"],
                "cost_rank": 11,
                "delivery_time_rank": 2,
                "easyship_courier_id": "de8835b8-17c5-4878-b636-9f9fdbab9265",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 1,
                "min_delivery_time": 1,
                "rate_provider": "fedex",
                "service_name": "easyship_fedex_standard_overnight",
                "tracking_rating": 3,
                "value_for_money_rank": 10,
            },
            "service": "easyship_fedex_standard_overnight",
            "total_charge": 234.73,
            "transit_days": 1,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 210.72, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 33.19, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff"],
                "cost_rank": 12,
                "delivery_time_rank": 1,
                "easyship_courier_id": "8fb58899-7c4d-43b3-be2c-ec4c2d3ba375",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 1,
                "min_delivery_time": 1,
                "rate_provider": "fedex",
                "service_name": "easyship_fedex_priority_overnight",
                "tracking_rating": 3,
                "value_for_money_rank": 11,
            },
            "service": "easyship_fedex_priority_overnight",
            "total_charge": 243.91,
            "transit_days": 1,
        },
        {
            "carrier_id": "easyship",
            "carrier_name": "easyship",
            "currency": "USD",
            "extra_charges": [
                {"amount": 170.04, "currency": "USD", "name": "Shipment Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Insurance"},
                {"amount": 26.78, "currency": "USD", "name": "Fuel Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Additional Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Duty Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Import Tax Charge"},
                {"amount": 0.0, "currency": "USD", "name": "Minimum Pickup Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Oversized Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Provincial Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Remote Area Surcharge"},
                {"amount": 0.0, "currency": "USD", "name": "Sales Tax"},
                {"amount": 0.0, "currency": "USD", "name": "Warehouse Handling Fee"},
                {"amount": 0.0, "currency": "USD", "name": "Discount"},
            ],
            "meta": {
                "available_handover_options": ["dropoff"],
                "cost_rank": 10,
                "delivery_time_rank": 4,
                "easyship_courier_id": "5eee483f-1416-42bb-8f7d-3ad384f3ee36",
                "easyship_incoterms": "DDU",
                "max_delivery_time": 2,
                "min_delivery_time": 2,
                "rate_provider": "fedex",
                "service_name": "easyship_fedex_2_day_a_m",
                "tracking_rating": 3,
                "value_for_money_rank": 12,
            },
            "service": "easyship_fedex_2_day_a_m",
            "total_charge": 196.82,
            "transit_days": 2,
        },
    ],
    [],
]


RateRequest = {
    "courier_selection": {
        "apply_shipping_rules": True,
        "show_courier_logo_url": False,
    },
    "destination_address": {
        "company_name": "N/A",
        "country_alpha2": "HK",
        "city": "Hong Kong",
        "contact_email": "asd@asd.com",
        "contact_name": "Foo Bar",
        "line_1": "Kennedy Town",
        "line_2": "Block 3",
        "postal_code": "0000",
        "state": "Yuen Long",
    },
    "incoterms": "DDU",
    "insurance": {
        "is_insured": False,
    },
    "origin_address": {
        "company_name": "N/A",
        "city": "Hong Kong",
        "contact_email": "asd@asd.com",
        "contact_name": "Foo Bar",
        "country_alpha2": "HK",
        "line_1": "Kennedy Town",
        "line_2": "Block 3",
        "postal_code": "0000",
        "state": "Yuen Long",
    },
    "parcels": [
        {
            "box": {
                "height": 3.0,
                "length": 1.0,
                "width": 2.0,
            },
            "items": [
                {
                    "contains_battery_pi966": True,
                    "contains_battery_pi967": True,
                    "contains_liquids": True,
                    "declared_currency": "USD",
                    "origin_country_alpha2": "HK",
                    "quantity": 2,
                    "actual_weight": 10.0,
                    "category": "fashion",
                    "declared_customs_value": 20,
                    "description": "item",
                    "sku": "sku",
                    "hs_code": "N/A",
                }
            ],
            "total_actual_weight": 1.0,
        }
    ],
    "shipping_settings": {"units": {"dimensions": "cm", "weight": "kg"}},
}

RateResponse = """{
  "rates": [
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff"],
      "cost_rank": 2,
      "courier_id": "4cf66d63-4e4a-456b-86c1-50964ad9f7b7",
      "courier_logo_url": null,
      "courier_name": "FedEx Ground®",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 6,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 5.59,
      "full_description": "FedEx Ground® (1-3 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 3,
      "min_delivery_time": 1,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 5.59,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 34.96,
        "shipment_charge_total": 40.55,
        "total_charge": 40.55,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 34.96,
      "shipment_charge_total": 40.55,
      "total_charge": 40.55,
      "tracking_rating": 3,
      "value_for_money_rank": 1,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff", "free_pickup"],
      "cost_rank": 5,
      "courier_id": "7505df80-af51-46a0-b2ee-ac9eacfcd3e4",
      "courier_logo_url": null,
      "courier_name": "USPS - Priority Mail",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 8,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 0,
      "full_description": "USPS - Priority Mail (1-3 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 3,
      "min_delivery_time": 1,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 0,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 76.2,
        "shipment_charge_total": 76.2,
        "total_charge": 76.2,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 76.2,
      "shipment_charge_total": 76.2,
      "total_charge": 76.2,
      "tracking_rating": 2,
      "value_for_money_rank": 2,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff", "free_pickup"],
      "cost_rank": 6,
      "courier_id": "137a79e8-ae1c-4369-9855-44cf8ff784c4",
      "courier_logo_url": null,
      "courier_name": "USPS - Priority Mail Signature",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 7,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 0,
      "full_description": "USPS - Priority Mail Signature (1-3 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 3,
      "min_delivery_time": 1,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 0,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 79.9,
        "shipment_charge_total": 79.9,
        "total_charge": 79.9,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 79.9,
      "shipment_charge_total": 79.9,
      "total_charge": 79.9,
      "tracking_rating": 2,
      "value_for_money_rank": 3,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff"],
      "cost_rank": 1,
      "courier_id": "eac604a4-34c9-41b6-b5b1-231fb785d071",
      "courier_logo_url": null,
      "courier_name": "FedEx Ground® Economy",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 10,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 0,
      "full_description": "FedEx Ground® Economy (2-5 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 5,
      "min_delivery_time": 2,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 0,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 26.29,
        "shipment_charge_total": 26.29,
        "total_charge": 26.29,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 26.29,
      "shipment_charge_total": 26.29,
      "total_charge": 26.29,
      "tracking_rating": 3,
      "value_for_money_rank": 4,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff", "free_pickup"],
      "cost_rank": 3,
      "courier_id": "c3e97b11-2842-44f1-84d1-afaa6b3f0a7c",
      "courier_logo_url": null,
      "courier_name": "USPS - Ground Advantage",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 12,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 0,
      "full_description": "USPS - Ground Advantage (2-5 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 5,
      "min_delivery_time": 2,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 0,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 48.56,
        "shipment_charge_total": 48.56,
        "total_charge": 48.56,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 48.56,
      "shipment_charge_total": 48.56,
      "total_charge": 48.56,
      "tracking_rating": 2,
      "value_for_money_rank": 5,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff", "free_pickup"],
      "cost_rank": 4,
      "courier_id": "7a1424ff-0d4e-4d55-bdfe-e4c6661debbf",
      "courier_logo_url": null,
      "courier_name": "USPS - Ground Advantage Signature",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 11,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 0,
      "full_description": "USPS - Ground Advantage Signature (2-5 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 5,
      "min_delivery_time": 2,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 0,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 52.26,
        "shipment_charge_total": 52.26,
        "total_charge": 52.26,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 52.26,
      "shipment_charge_total": 52.26,
      "total_charge": 52.26,
      "tracking_rating": 2,
      "value_for_money_rank": 6,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff"],
      "cost_rank": 7,
      "courier_id": "84135827-1538-4be2-b26e-afd8b3f3b4bd",
      "courier_logo_url": null,
      "courier_name": "FedEx 2Day®",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 5,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 0,
      "full_description": "FedEx 2Day® (2 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 2,
      "min_delivery_time": 2,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 0,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 91.69,
        "shipment_charge_total": 91.69,
        "total_charge": 91.69,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 91.69,
      "shipment_charge_total": 91.69,
      "total_charge": 91.69,
      "tracking_rating": 3,
      "value_for_money_rank": 7,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff", "free_pickup"],
      "cost_rank": 9,
      "courier_id": "a623a62b-5631-4dce-ae15-bbcf89e49c52",
      "courier_logo_url": null,
      "courier_name": "USPS - Priority Mail Express",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 3,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 0,
      "full_description": "USPS - Priority Mail Express (1-2 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 2,
      "min_delivery_time": 1,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 0,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 180.55,
        "shipment_charge_total": 180.55,
        "total_charge": 180.55,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 180.55,
      "shipment_charge_total": 180.55,
      "total_charge": 180.55,
      "tracking_rating": 2,
      "value_for_money_rank": 8,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff"],
      "cost_rank": 8,
      "courier_id": "a9e3f424-713c-4efa-b445-71cd60c88ccd",
      "courier_logo_url": null,
      "courier_name": "FedEx Express Saver®",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 9,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 19,
      "full_description": "FedEx Express Saver® (2-3 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 3,
      "min_delivery_time": 2,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 19,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 120.64,
        "shipment_charge_total": 139.64,
        "total_charge": 139.64,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 120.64,
      "shipment_charge_total": 139.64,
      "total_charge": 139.64,
      "tracking_rating": 3,
      "value_for_money_rank": 9,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff"],
      "cost_rank": 11,
      "courier_id": "de8835b8-17c5-4878-b636-9f9fdbab9265",
      "courier_logo_url": null,
      "courier_name": "FedEx Standard Overnight®",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 2,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 31.94,
      "full_description": "FedEx Standard Overnight® (1 working day) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 1,
      "min_delivery_time": 1,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 31.94,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 202.79,
        "shipment_charge_total": 234.73,
        "total_charge": 234.73,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 202.79,
      "shipment_charge_total": 234.73,
      "total_charge": 234.73,
      "tracking_rating": 3,
      "value_for_money_rank": 10,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff"],
      "cost_rank": 12,
      "courier_id": "8fb58899-7c4d-43b3-be2c-ec4c2d3ba375",
      "courier_logo_url": null,
      "courier_name": "FedEx Priority Overnight®",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 1,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 33.19,
      "full_description": "FedEx Priority Overnight® (1 working day) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 1,
      "min_delivery_time": 1,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 33.19,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 210.72,
        "shipment_charge_total": 243.91,
        "total_charge": 243.91,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 210.72,
      "shipment_charge_total": 243.91,
      "total_charge": 243.91,
      "tracking_rating": 3,
      "value_for_money_rank": 11,
      "warehouse_handling_fee": 0
    },
    {
      "additional_services_surcharge": 0,
      "available_handover_options": ["dropoff"],
      "cost_rank": 10,
      "courier_id": "5eee483f-1416-42bb-8f7d-3ad384f3ee36",
      "courier_logo_url": null,
      "courier_name": "FedEx 2Day® A.M.",
      "courier_remarks": null,
      "currency": "USD",
      "ddp_handling_fee": 0,
      "delivery_time_rank": 4,
      "description": "No additional taxes to be paid at delivery",
      "discount": { "amount": 0, "origin_amount": 0 },
      "easyship_rating": null,
      "estimated_import_duty": 0,
      "estimated_import_tax": 0,
      "fuel_surcharge": 26.78,
      "full_description": "FedEx 2Day® A.M. (2 working days) No additional taxes to be paid at delivery",
      "import_duty_charge": 0,
      "import_tax_charge": 0,
      "import_tax_non_chargeable": 0,
      "incoterms": "DDU",
      "insurance_fee": 0,
      "is_above_threshold": false,
      "max_delivery_time": 2,
      "min_delivery_time": 2,
      "minimum_pickup_fee": 0,
      "other_surcharges": null,
      "oversized_surcharge": 0,
      "payment_recipient": "Easyship",
      "provincial_sales_tax": 0,
      "rates_in_origin_currency": {
        "additional_services_surcharge": 0,
        "currency": "USD",
        "ddp_handling_fee": 0,
        "estimated_import_duty": 0,
        "estimated_import_tax": 0,
        "fuel_surcharge": 26.78,
        "import_duty_charge": 0,
        "import_tax_charge": 0,
        "import_tax_non_chargeable": 0,
        "insurance_fee": 0,
        "minimum_pickup_fee": 0,
        "oversized_surcharge": 0,
        "provincial_sales_tax": 0,
        "remote_area_surcharge": 0,
        "residential_discounted_fee": null,
        "residential_full_fee": null,
        "sales_tax": 0,
        "shipment_charge": 170.04,
        "shipment_charge_total": 196.82,
        "total_charge": 196.82,
        "warehouse_handling_fee": 0
      },
      "remote_area_surcharge": 0,
      "remote_area_surcharges": null,
      "residential_discounted_fee": null,
      "residential_full_fee": null,
      "sales_tax": 0,
      "shipment_charge": 170.04,
      "shipment_charge_total": 196.82,
      "total_charge": 196.82,
      "tracking_rating": 3,
      "value_for_money_rank": 12,
      "warehouse_handling_fee": 0
    }
  ],
  "meta": {
    "pagination": { "page": 1, "next": null, "count": 12 },
    "request_id": "269d0680c54e55d25df3fa09191f07ad"
  }
}
"""
