# Generated by Django 3.1.2 on 2020-10-21 04:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_pickup_pickup_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickup_charge',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
