import base64
import io
from barcode import Code128
from barcode.writer import ImageWriter

ORDER_SAMPLE = dict(
    order={
        "id": "ord_028e5cb83814487a9546d0690260f0ee",
        "object_type": "order",
        "order_id": "1073459962",
        "source": "shopify",
        "status": "unfulfilled",
        "shipping_to": {
            "id": "adr_4e038ec1bf4448d284069d0dfd761fb3",
            "postal_code": "E1C4Z8",
            "city": "Moncton",
            "federal_tax_id": None,
            "state_tax_id": None,
            "person_name": "John Doe",
            "company_name": "A corp.",
            "country_code": "CA",
            "email": None,
            "phone_number": "+1 514-000-0000",
            "state_code": "NB",
            "suburb": None,
            "residential": False,
            "address_line1": "125 Church St",
            "address_line2": None,
            "validate_location": False,
            "object_type": "address",
            "validation": None,
        },
        "shipping_from": None,
        "line_items": [
            {
                "id": "cdt_cd32372be5524a2fa492c4af598b7679",
                "weight": 0.75,
                "weight_unit": "KG",
                "description": "Violet Suede Shoes",
                "quantity": 1,
                "sku": None,
                "value_amount": 85.95,
                "value_currency": "USD",
                "origin_country": None,
                "parent_id": None,
                "metadata": {
                    "BGM": "040000000000016256",
                    "CTL": "11253678",
                    "DEPT": "DBR128",
                    "XXNC": "138039C01",
                    "NAD_UD": "570162",
                    "RFF_CN": "037-2332855",
                    "RFF_ON": "5424560",
                    "RFF_AEM": "3901L",
                    "RFF_AJY": "907",
                },
                "object_type": "commodity",
            },
            {
                "id": "cdt_71ef30b72d4c4b94882337b44e0d3fb9",
                "weight": 1.7,
                "weight_unit": "KG",
                "description": "Purple Leather Coat",
                "quantity": 1,
                "sku": None,
                "value_amount": 129.99,
                "value_currency": "USD",
                "origin_country": None,
                "parent_id": None,
                "metadata": {
                    "BGM": "040000000000016256",
                    "CTL": "11253678",
                    "DEPT": "DBR128",
                    "XXNC": "138039C01",
                    "NAD_UD": "570162",
                    "RFF_CN": "037-2332855",
                    "RFF_ON": "5424560",
                    "RFF_AEM": "3901L",
                    "RFF_AJY": "907",
                },
                "object_type": "commodity",
            },
        ],
        "options": {},
        "metadata": {},
        "shipments": [],
        "test_mode": True,
        "created_at": "2022-03-11 22:33:52.123894+00:00",
    },
    fulfilments=[
        dict(
            item={
                "id": "cdt_cd32372be5524a2fa492c4af598b7679",
                "weight": 0.75,
                "weight_unit": "KG",
                "description": "Violet Suede Shoes",
                "quantity": 1,
                "sku": None,
                "value_amount": 85.95,
                "value_currency": "USD",
                "origin_country": None,
                "parent_id": None,
                "metadata": {
                    "BGM": "040000000000016256",
                    "CTL": "11253678",
                    "DEPT": "DBR128",
                    "XXNC": "138039C01",
                    "NAD_UD": "570162",
                    "RFF_CN": "037-2332855",
                    "RFF_ON": "5424560",
                    "RFF_AEM": "3901L",
                    "RFF_AJY": "907",
                },
                "object_type": "commodity",
            },
            fulfilled_quantity=1,
        ),
        dict(
            item={
                "id": "cdt_71ef30b72d4c4b94882337b44e0d3fb9",
                "weight": 1.7,
                "weight_unit": "KG",
                "description": "Purple Leather Coat",
                "quantity": 1,
                "sku": None,
                "value_amount": 129.99,
                "value_currency": "USD",
                "origin_country": None,
                "parent_id": None,
                "metadata": {
                    "BGM": "040000000000016256",
                    "CTL": "11253678",
                    "DEPT": "DBR128",
                    "XXNC": "138039C01",
                    "NAD_UD": "570162",
                    "RFF_CN": "037-2332855",
                    "RFF_ON": "5424560",
                    "RFF_AEM": "3901L",
                    "RFF_AJY": "907",
                },
                "object_type": "commodity",
            },
            fulfilled_quantity=1,
        ),
    ],
)

SHIPMENT_SAMPLE = dict(
    shipment={
        "id": "shp_443a79f813674397bedb0309148a12c6",
        "object_type": "shipment",
        "tracking_url": "/v1/trackers/tst_overland/0000000154?test",
        "shipper": {
            "id": "adr_f46e47cbb4b047658d70fc8e0593309b",
            "postal_code": "E1C4Z8",
            "city": "Moncton",
            "federal_tax_id": None,
            "state_tax_id": None,
            "person_name": "John Doe",
            "company_name": "A corp.",
            "country_code": "CA",
            "email": None,
            "phone_number": "+1 514-000-0000",
            "state_code": "NB",
            "suburb": None,
            "residential": False,
            "address_line1": "125 Church St",
            "address_line2": None,
            "validate_location": None,
            "object_type": "address",
            "validation": None,
        },
        "recipient": {
            "id": "adr_6d8bd1716df947ed84b394b2e4e33a03",
            "postal_code": "V6M2V9",
            "city": "Vancouver",
            "federal_tax_id": None,
            "state_tax_id": None,
            "person_name": "Jane Doe",
            "company_name": "B corp.",
            "country_code": "CA",
            "email": None,
            "phone_number": "+1 514-000-0000",
            "state_code": "BC",
            "suburb": None,
            "residential": True,
            "address_line1": "5840 Oak St",
            "address_line2": None,
            "validate_location": None,
            "object_type": "address",
            "validation": None,
        },
        "parcels": [
            {
                "id": "pcl_58848b4987d54b999d180be5a1fec83e",
                "weight": 1.0,
                "width": 46.0,
                "height": 38.0,
                "length": 32.0,
                "packaging_type": None,
                "package_preset": "canadapost_corrugated_medium_box",
                "description": None,
                "content": None,
                "is_document": False,
                "weight_unit": "KG",
                "dimension_unit": "CM",
                "items": [
                    {
                        "id": "cdt_04e2d1cc865e495aaced676d82764a14",
                        "weight": 1.7,
                        "weight_unit": "KG",
                        "description": "Brown Leather Jacket",
                        "quantity": 3,
                        "sku": "1000044",
                        "value_amount": 150.0,
                        "value_currency": "USD",
                        "origin_country": None,
                        "parent_id": None,
                        "metadata": {
                            "BGM": "040000000000016256",
                            "CTL": "11253678",
                            "DEPT": "DBR128",
                            "XXNC": "138039C01",
                            "NAD_UD": "570162",
                            "RFF_CN": "037-2332855",
                            "RFF_ON": "5424560",
                            "RFF_AEM": "3901L",
                            "RFF_AJY": "907",
                        },
                        "object_type": "commodity",
                    }
                ],
                "reference_number": "0000000154",
                "object_type": "parcel",
            }
        ],
        "services": [],
        "options": {},
        "payment": {"paid_by": "sender", "currency": None, "account_number": None},
        "customs": None,
        "rates": [
            {
                "id": "rat_68e26d10faaf4499a7781475e2b34999",
                "object_type": "rate",
                "carrier_name": "tst_overland",
                "carrier_id": "tst-overland",
                "currency": "CAD",
                "service": "standard_service",
                "discount": None,
                "base_charge": 100.0,
                "total_charge": 100.0,
                "duties_and_taxes": None,
                "transit_days": None,
                "extra_charges": [],
                "meta": {
                    "carrier_connection_id": "car_9dac728533e841b09ec453178de5b3c3",
                    "rate_provider": "tst_overland",
                    "service_name": "STANDARD SERVICE",
                },
                "test_mode": True,
            }
        ],
        "reference": None,
        "label_type": "PDF",
        "carrier_ids": [],
        "tracker_id": None,
        "created_at": "2022-03-10 04:11:44.885509+00:00",
        "metadata": {},
        "messages": [],
        "status": "purchased",
        "carrier_name": "generic",
        "carrier_id": "tst-overland",
        "tracking_number": "0000000154",
        "shipment_identifier": "0000000154",
        "selected_rate": {
            "id": "rat_68e26d10faaf4499a7781475e2b34999",
            "object_type": "rate",
            "carrier_name": "tst_overland",
            "carrier_id": "tst-overland",
            "currency": "CAD",
            "service": "standard_service",
            "discount": None,
            "base_charge": 100.0,
            "total_charge": 100.0,
            "duties_and_taxes": None,
            "transit_days": None,
            "extra_charges": [],
            "meta": {
                "carrier_connection_id": "car_9dac728533e841b09ec453178de5b3c3",
                "rate_provider": "tst_overland",
                "service_name": "STANDARD SERVICE",
            },
            "test_mode": True,
        },
        "meta": {"service_name": "STANDARD SERVICE", "rate_provider": "generic"},
        "service": "standard_service",
        "selected_rate_id": "rat_68e26d10faaf4499a7781475e2b34999",
        "test_mode": True,
        "label_url": "/v1/shipments/shp_443a79f813674397bedb0309148a12c6/label.pdf",
        "invoice_url": None,
    },
    carrier={
        "id": "car_9dac728533e841b09ec453178de5b3c3",
        "display_name": "TST Overland",
        "carrier_name": "tst_overland",
        "carrier_id": "tst-overland",
        "test": True,
        "active": True,
        "object_type": "carrier",
        "metadata": {
            "APP_ID": "00",
            "EXTENSION_DIGIT": "0",
            "GS1_PREFIX": "0099999000",
            "CHECK_DIGIT": "5",
        },
    },
)


def create_barcode(value) -> str:
    barcode = Code128(value, writer=ImageWriter()).render(
        writer_options=dict(
            quiet_zone=1.0,
            module_width=0.5,
            module_height=30.0,
            font_size=1,
            text_distance=0.0,
            dpi=300,
        ),
        text="",
    )
    buffer = io.BytesIO()
    barcode.save(buffer, "PNG")

    return base64.b64encode(buffer.getvalue()).decode("utf-8")
