# Generated by Django 3.1.4 on 2020-12-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
