# Generated by Django 4.1.3 on 2022-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0044_carrier_carrier_capabilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Disable/Hide carrier from clients",
            ),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="carrier_id",
            field=models.CharField(
                db_index=True,
                help_text="eg. canadapost, dhl_express, fedex, purolator_courrier, ups...",
                max_length=200,
            ),
        ),
    ]
