# Generated by Django 4.2.7 on 2023-11-07 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0055_rename_amazonmwssettings_amazonshippingsettings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsendiaUSSettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Asendia US Settings",
                "verbose_name_plural": "Asendia US Settings",
                "db_table": "asendia-us-settings",
            },
            bases=("providers.carrier",),
        ),
        migrations.AddField(
            model_name="geodissettings",
            name="code_client",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ColissimoSettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                ("contract_number", models.CharField(max_length=100)),
                ("laposte_api_key", models.CharField(blank=True, max_length=100)),
                (
                    "services",
                    models.ManyToManyField(blank=True, to="providers.servicelevel"),
                ),
            ],
            options={
                "verbose_name": "Colissimo Settings",
                "verbose_name_plural": "Colissimo Settings",
                "db_table": "colissimo-settings",
            },
            bases=("providers.carrier",),
        ),
    ]
