# Generated by Django 4.2.8 on 2023-12-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0059_ratesheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="belgianpostsettings",
            name="rate_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="providers.ratesheet",
            ),
        ),
        migrations.AddField(
            model_name="colissimosettings",
            name="rate_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="providers.ratesheet",
            ),
        ),
        migrations.AddField(
            model_name="dhlpolandsettings",
            name="rate_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="providers.ratesheet",
            ),
        ),
        migrations.AddField(
            model_name="dpdhlsettings",
            name="rate_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="providers.ratesheet",
            ),
        ),
        migrations.AddField(
            model_name="dpdsettings",
            name="rate_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="providers.ratesheet",
            ),
        ),
        migrations.AddField(
            model_name="genericsettings",
            name="rate_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="providers.ratesheet",
            ),
        ),
    ]
