# Generated by Django 4.2.8 on 2023-12-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0060_belgianpostsettings_rate_sheet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliedexpresssettings",
            name="service_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
