# Generated by Django 4.2.10 on 2024-02-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0065_servicelevel_carrier_service_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FedexSettings",
            new_name="FedexWSSettings",
        ),
        migrations.AlterModelOptions(
            name="fedexwssettings",
            options={
                "verbose_name": "FedEx Web Service Settings",
                "verbose_name_plural": "FedEx Web Service Settings",
            },
        ),
        migrations.AlterModelTable(
            name="fedexwssettings",
            table="fedex-ws-settings",
        ),
    ]
