# Generated by Django 4.2.10 on 2024-03-14 23:35

from django.db import migrations, models
import django.db.models.deletion
import functools
import karrio.server.core.fields
import karrio.server.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0069_alter_canadapostsettings_contract_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TGESettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=100)),
                ("toll_username", models.CharField(max_length=100)),
                ("toll_password", models.CharField(max_length=100)),
                ("my_toll_token", models.CharField(max_length=250)),
                ("my_toll_identity", models.CharField(max_length=100)),
                ("account_code", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "TGE Settings",
                "verbose_name_plural": "TGE Settings",
                "db_table": "tge-settings",
            },
            bases=("providers.carrier",),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="capabilities",
            field=karrio.server.core.fields.MultiChoiceField(
                choices=[
                    ("pickup", "pickup"),
                    ("rating", "rating"),
                    ("shipping", "shipping"),
                    ("tracking", "tracking"),
                    ("paperless", "paperless"),
                    ("manifest", "manifest"),
                ],
                default=functools.partial(
                    karrio.server.core.models._identity, *(), **{"value": []}
                ),
                help_text="Select the capabilities of the carrier that you want to enable",
            ),
        ),
    ]
