# Generated by Django 4.2.11 on 2024-07-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0073_delete_eshipperxmlsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="EShipperSettings",
            fields=[
                (
                    "carrier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="providers.carrier",
                    ),
                ),
                ("principal", models.CharField(max_length=100)),
                ("credential", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "eShipper Settings",
                "verbose_name_plural": "eShipper Settings",
                "db_table": "eshipper-settings",
            },
            bases=("providers.carrier",),
        ),
    ]
