# Generated by Django 4.1.6 on 2023-02-04 09:40

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_event_object_idx"),
    ]

    operations = []

    if "postgres" in settings.DB_ENGINE:
        operations = [
            migrations.RunSQL('ALTER TABLE "webhook" ALTER COLUMN "enabled_events" TYPE jsonb USING to_jsonb(enabled_events)'),
        ]
