# Generated by Django 4.2 on 2023-04-18 10:18

from django.db import migrations
import functools
import karrio.server.core.fields
import karrio.server.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="enabled_events",
            field=karrio.server.core.fields.MultiChoiceField(
                choices=[
                    ("all", "all"),
                    ("shipment_purchased", "shipment_purchased"),
                    ("shipment_cancelled", "shipment_cancelled"),
                    ("shipment_fulfilled", "shipment_fulfilled"),
                    ("shipment_out_for_delivery", "shipment_out_for_delivery"),
                    ("shipment_needs_attention", "shipment_needs_attention"),
                    ("shipment_delivery_failed", "shipment_delivery_failed"),
                    ("tracker_created", "tracker_created"),
                    ("tracker_updated", "tracker_updated"),
                    ("order_created", "order_created"),
                    ("order_updated", "order_updated"),
                    ("order_fulfilled", "order_fulfilled"),
                    ("order_cancelled", "order_cancelled"),
                    ("order_delivered", "order_delivered"),
                    ("batch_queued", "batch_queued"),
                    ("batch_failed", "batch_failed"),
                    ("batch_running", "batch_running"),
                    ("batch_completed", "batch_completed"),
                ],
                default=functools.partial(
                    karrio.server.core.models._identity, *(), **{"value": []}
                ),
                help_text="Webhook events",
            ),
        ),
    ]
