# Generated by Django 5.2.3 on 2025-06-15 05:13

import django.db.models.deletion
import functools
import karrio.server.core.models.base
import karrio.server.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_remove_appinstallation_app_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstallation",
            name="app_id",
            field=models.CharField(
                default="temp",
                help_text="ID of the physical app from the app store manifest",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appinstallation",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("builtin", "Built-in App"),
                    ("marketplace", "Marketplace App"),
                    ("private", "Private App"),
                ],
                default="marketplace",
                help_text="Type of the installed app",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appinstallation",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appinstallation",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this app installation is currently active",
            ),
        ),
        migrations.AlterField(
            model_name="appinstallation",
            name="access_scopes",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": []}
                ),
                help_text="Scopes granted to this app installation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appinstallation",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": {}}
                ),
                help_text="Installation-specific metadata and settings",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appinstallation",
            unique_together={("created_by", "app_id")},
        ),
        migrations.CreateModel(
            name="OAuthApp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=functools.partial(
                            karrio.server.core.models.base.uuid,
                            *(),
                            **{"prefix": "app_"}
                        ),
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("launch_url", models.URLField(max_length=500)),
                ("redirect_uris", models.TextField()),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=functools.partial(
                            karrio.server.core.utils.identity, *(), **{"value": []}
                        ),
                        help_text="List of features this OAuth app supports",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=functools.partial(
                            karrio.server.core.utils.identity, *(), **{"value": {}}
                        ),
                        help_text="Additional metadata for the OAuth app",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_app",
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth App",
                "verbose_name_plural": "OAuth Apps",
                "db_table": "oauth-app",
                "ordering": ["-created_at"],
            },
            bases=(karrio.server.core.models.base.ControlledAccessModel, models.Model),
        ),
        migrations.AddField(
            model_name="appinstallation",
            name="oauth_app",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated OAuth app if this installation requires OAuth",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installations",
                to="apps.oauthapp",
            ),
        ),
        migrations.DeleteModel(
            name="App",
        ),
    ]
