# Generated by Django 3.2.13 on 2022-07-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'verbose_name': 'log entry', 'verbose_name_plural': 'log entries'},
        ),
    ]
