# Generated by Django 4.2.8 on 2024-01-13 23:05

from django.db import migrations, models, transaction
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Metafield = apps.get_model("core", "Metafield")
    WorkflowConnection = apps.get_model("automation", "WorkflowConnection")

    with transaction.atomic():
        # -----------------------------------------------------------
        # Create workflow connection templates
        # -----------------------------------------------------------
        # region

        _shopify_connection = WorkflowConnection.objects.using(db_alias).filter(
            slug="$.shopify-access-token.workflow.connection",
            metafields__isnull=True,
        )

        if _shopify_connection.exists():
            _shopify_connection.first().metafields.set(
                [
                    Metafield.objects.using(db_alias).create(
                        key="access_token",
                        type="text",
                        is_required=True,
                    ),
                ]
            )

        _karrio_connection = WorkflowConnection.objects.using(db_alias).filter(
            slug="$.karrio-token.workflow.connection",
            metafields__isnull=True,
        )

        if _karrio_connection.exists():
            _karrio_connection.first().metafields.set(
                [
                    Metafield.objects.using(db_alias).create(
                        key="token",
                        type="text",
                        is_required=True,
                    ),
                ]
            )

        # endregion


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_metafield"),
        ("automation", "0002_auto_20231227_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="name"),
        ),
        migrations.CreateModel(
            name="WorkflowConnectionMetafieldLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields_links",
                        to="automation.workflowconnection",
                    ),
                ),
                (
                    "metafield",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_link",
                        to="core.metafield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowActionMetafieldLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields_links",
                        to="automation.workflowaction",
                    ),
                ),
                (
                    "metafield",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_link",
                        to="core.metafield",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="metafields",
            field=models.ManyToManyField(
                related_name="metafield_action",
                through="automation.WorkflowActionMetafieldLink",
                to="core.metafield",
            ),
        ),
        migrations.AddField(
            model_name="workflowconnection",
            name="metafields",
            field=models.ManyToManyField(
                related_name="metafield_connection",
                through="automation.WorkflowConnectionMetafieldLink",
                to="core.metafield",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
