# Generated by Django 5.2.2 on 2025-06-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_shippingrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtrigger",
            name="last_run_at",
            field=models.DateTimeField(
                blank=True, help_text="Last execution time", null=True
            ),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="next_run_at",
            field=models.DateTimeField(
                blank=True, help_text="Next scheduled execution time", null=True
            ),
        ),
    ]
