# Generated by Django 3.2.12 on 2022-03-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_shipment_invoice'),
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manager.commodity',),
        ),
        migrations.AlterField(
            model_name='order',
            name='line_items',
            field=models.ManyToManyField(related_name='commodity_order', through='orders.OrderLineItemLink', to='orders.LineItem'),
        ),
        migrations.AlterField(
            model_name='orderlineitemlink',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_link', to='orders.lineitem'),
        ),
    ]
