# Generated by Django 4.1.3 on 2022-11-28 18:39

from django.db import migrations, models
import functools
import karrio.server.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_order_order_id_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": {}}
                ),
                null=True,
            ),
        ),
    ]
