from kcli.templates.address import *
from kcli.templates.docs import *
from kcli.templates.documents import *
from kcli.templates.manifest import *
from kcli.templates.pickup import *
from kcli.templates.rates import *
from kcli.templates.sdk import *
from kcli.templates.shipments import *
from kcli.templates.tracking import *
