#!/bin/bash

# Set paths
SCHEMAS=./schemas
LIB_MODULES=./karrio/schemas/dtdc
find "${LIB_MODULES}" -name "*.py" -exec rm -r {} \;
touch "${LIB_MODULES}/__init__.py"

# Generate Python classes from JSON schemas
# Using --nice-property-names for snake_case API fields
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/error_response.json" "${LIB_MODULES}/error_response.py" --no-nice-property-names
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/label_response.json" "${LIB_MODULES}/label_response.py" --no-nice-property-names
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/shipment_request.json" "${LIB_MODULES}/shipment_request.py" --nice-property-names
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/shipment_response.json" "${LIB_MODULES}/shipment_response.py" --nice-property-names
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/tracking_request.json" "${LIB_MODULES}/tracking_request.py" --no-nice-property-names
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/tracking_response.json" "${LIB_MODULES}/tracking_response.py" --no-nice-property-names
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/shipment_cancel_request.json" "${LIB_MODULES}/shipment_cancel_request.py" --no-nice-property-names
"${ROOT}/bin/cli" codegen generate "${SCHEMAS}/shipment_cancel_response.json" "${LIB_MODULES}/shipment_cancel_response.py" --no-nice-property-names

