# Generated by Django 3.2.10 on 2022-01-26 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0024_alter_genericsettings_custom_carrier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelevel',
            name='service_code',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$')]),
        ),
    ]
