# Generated by Django 3.2.13 on 2022-06-17 18:39

import functools

import karrio.server.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0034_commodity_hs_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="options",
            field=models.JSONField(
                blank=True,
                default=functools.partial(karrio.server.core.utils.identity, *(), **{"value": {}}),
                null=True,
            ),
        ),
    ]
