# Generated by Django 4.1.4 on 2023-01-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0044_address_address_line1_temp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customs",
            name="duty_billing_address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duty_billing_address_customs",
                to="manager.address",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="billing_address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_address_shipment",
                to="manager.address",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="customs",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customs_shipment",
                to="manager.customs",
            ),
        ),
    ]
