# Generated by Django 4.2.8 on 2023-12-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0054_alter_address_company_name_alter_address_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("unknown", "unknown"),
                    ("on_hold", "on_hold"),
                    ("delivered", "delivered"),
                    ("in_transit", "in_transit"),
                    ("delivery_delayed", "delivery_delayed"),
                    ("out_for_delivery", "out_for_delivery"),
                    ("ready_for_pickup", "ready_for_pickup"),
                    ("delivery_failed", "delivery_failed"),
                ],
                db_index=True,
                default="pending",
                max_length=25,
            ),
        ),
    ]
