# Generated by Django 4.2.16 on 2025-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0061_alter_customs_incoterm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("unknown", "unknown"),
                    ("on_hold", "on_hold"),
                    ("cancelled", "cancelled"),
                    ("delivered", "delivered"),
                    ("in_transit", "in_transit"),
                    ("delivery_delayed", "delivery_delayed"),
                    ("out_for_delivery", "out_for_delivery"),
                    ("ready_for_pickup", "ready_for_pickup"),
                    ("delivery_failed", "delivery_failed"),
                    ("return_to_sender", "return_to_sender"),
                ],
                db_index=True,
                default="pending",
                max_length=25,
            ),
        ),
    ]
