# Generated by Django 5.2.7 on 2025-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0065_alter_address_city_alter_address_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="image_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="commodity",
            name="product_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="commodity",
            name="product_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="commodity",
            name="variant_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
