# Generated by Django 6.0 on 2025-12-12 20:16

import functools
import karrio.server.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0067_rename_customs_commodities_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='extra_documents',
            field=models.JSONField(blank=True, default=functools.partial(karrio.server.core.utils.identity, value=[]), null=True),
        ),
    ]
