# Generated by Django 5.2.9 on 2025-12-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0068_shipment_extra_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("picked_up", "picked_up"),
                    ("unknown", "unknown"),
                    ("on_hold", "on_hold"),
                    ("cancelled", "cancelled"),
                    ("delivered", "delivered"),
                    ("in_transit", "in_transit"),
                    ("delivery_delayed", "delivery_delayed"),
                    ("out_for_delivery", "out_for_delivery"),
                    ("ready_for_pickup", "ready_for_pickup"),
                    ("delivery_failed", "delivery_failed"),
                    ("return_to_sender", "return_to_sender"),
                ],
                db_index=True,
                default="pending",
                max_length=25,
            ),
        ),
    ]
