# Generated by Django 5.2.10 on 2026-01-16 00:43

import functools
import karrio.server.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0069_alter_tracking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": {}}
                ),
                help_text="Template metadata: label, is_default, usage[]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": {}}
                ),
                help_text="Template metadata: label, is_default",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="commodity",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": {}}
                ),
                help_text="Template metadata: label, is_default",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="billing_address_data",
            field=models.JSONField(
                blank=True, help_text="Billing address snapshot (JSON)", null=True
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="customs_data",
            field=models.JSONField(
                blank=True, help_text="Customs information snapshot (JSON)", null=True
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="parcels_data",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": []}
                ),
                help_text="Parcels array with items (JSON)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="recipient_data",
            field=models.JSONField(
                blank=True, help_text="Recipient address snapshot (JSON)", null=True
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="return_address_data",
            field=models.JSONField(
                blank=True, help_text="Return address snapshot (JSON)", null=True
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipper_data",
            field=models.JSONField(
                blank=True, help_text="Shipper address snapshot (JSON)", null=True
            ),
        ),
    ]
