# Generated by Django 5.2.10 on 2026-01-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0070_add_meta_and_product_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("manager.commodity",),
        ),
    ]
