# Generated by Django 5.2.10 on 2026-01-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0072_populate_json_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="recipient",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_shipment",
                to="manager.address",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipper",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipper_shipment",
                to="manager.address",
            ),
        ),
    ]
