# Generated by Django 5.2.10 on 2026-01-22 14:29

import functools
import karrio.server.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0080_add_carrier_json_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="billing_address",
            field=models.JSONField(
                blank=True, help_text="Billing address (embedded JSON)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="customs",
            field=models.JSONField(
                blank=True, help_text="Customs information (embedded JSON)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="parcels",
            field=models.JSONField(
                blank=True,
                default=functools.partial(
                    karrio.server.core.utils.identity, *(), **{"value": []}
                ),
                help_text="Parcels array with nested items (embedded JSON)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="recipient",
            field=models.JSONField(
                blank=True, help_text="Recipient address (embedded JSON)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="return_address",
            field=models.JSONField(
                blank=True, help_text="Return address (embedded JSON)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipper",
            field=models.JSONField(
                blank=True, help_text="Shipper address (embedded JSON)", null=True
            ),
        ),
    ]
