# Generated by Django 5.2.10 on 2026-01-29
# Adds applied_fees field to Shipment for tracking COGS accounting data

import functools
from django.db import migrations, models
import karrio.server.core.utils as utils


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0081_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="applied_fees",
            field=models.JSONField(
                blank=True,
                null=True,
                default=functools.partial(utils.identity, value=[]),
                help_text="Applied fees for accounting: addons + surcharge COGS values",
            ),
        ),
    ]
