# Generated by Django 5.2.10 on 2026-01-31
# Adds status field to Pickup for lifecycle management

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0082_shipment_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickup",
            name="status",
            field=models.CharField(
                db_index=True,
                default="scheduled",
                max_length=25,
            ),
        ),
    ]
