# Generated by Django 6.0.3 on 2026-04-02 00:57
#
# NOTE: The DB operations in this migration were originally a flat list of
# AddField operations. Those are not idempotent — in rolling-deploy scenarios
# where DDL partially landed on the database but the `django_migrations` row
# for this migration never got recorded (e.g. pod killed mid-apply, concurrent
# migrate invocations during a rollout), every subsequent `migrate` call on
# the stuck database raises `DuplicateColumn: column "archived_at" of
# relation "pickups" already exists` and blocks the entire deployment.
#
# The state operations are preserved exactly (so downstream migrations that
# depend on these fields continue to build correct project state), but the
# database operations are wrapped in a RunPython guard that introspects the
# existing columns and only adds what's missing. Behavior by upgrade path:
#
#   - Fresh install: columns are absent → RunPython adds all six.
#   - Already-applied user (2026.1.28): this migration is in django_migrations
#     and will not run again; the rewrite has no effect.
#   - Broken-state user: columns exist but migration record is missing →
#     RunPython finds the columns present, skips, and records the migration.

from django.db import migrations, models

ARCHIVING_TARGETS = ("pickup", "shipment", "tracking")


def _archived_at_field():
    field = models.DateTimeField(
        blank=True,
        null=True,
        help_text="Timestamp when the record was archived. Null if not archived.",
    )
    field.set_attributes_from_name("archived_at")
    return field


def _is_archived_field():
    field = models.BooleanField(
        db_index=True,
        default=False,
        help_text="Archived records are excluded from default queries and background jobs.",
    )
    field.set_attributes_from_name("is_archived")
    return field


def _existing_columns(schema_editor, model):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, model._meta.db_table)
        }


def forwards(apps, schema_editor):
    for model_name in ARCHIVING_TARGETS:
        model = apps.get_model("manager", model_name)
        existing = _existing_columns(schema_editor, model)
        if "archived_at" not in existing:
            schema_editor.add_field(model, _archived_at_field())
        if "is_archived" not in existing:
            schema_editor.add_field(model, _is_archived_field())


def backwards(apps, schema_editor):
    for model_name in ARCHIVING_TARGETS:
        model = apps.get_model("manager", model_name)
        existing = _existing_columns(schema_editor, model)
        for column_name in ("is_archived", "archived_at"):
            if column_name in existing:
                schema_editor.remove_field(model, model._meta.get_field(column_name))


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0089_rename_purchased_to_created_and_remove_choices"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="pickup",
                    name="archived_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was archived. Null if not archived.",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="pickup",
                    name="is_archived",
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Archived records are excluded from default queries and background jobs.",
                    ),
                ),
                migrations.AddField(
                    model_name="shipment",
                    name="archived_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was archived. Null if not archived.",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="shipment",
                    name="is_archived",
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Archived records are excluded from default queries and background jobs.",
                    ),
                ),
                migrations.AddField(
                    model_name="tracking",
                    name="archived_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was archived. Null if not archived.",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="tracking",
                    name="is_archived",
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Archived records are excluded from default queries and background jobs.",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(forwards, backwards),
            ],
        ),
    ]
