# Generated by Django 6.0.3 on 2026-04-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0089_rename_purchased_to_created_and_remove_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickup",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the record was archived. Null if not archived.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pickup",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Archived records are excluded from default queries and background jobs.",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the record was archived. Null if not archived.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Archived records are excluded from default queries and background jobs.",
            ),
        ),
        migrations.AddField(
            model_name="tracking",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the record was archived. Null if not archived.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tracking",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Archived records are excluded from default queries and background jobs.",
            ),
        ),
    ]
