from .rate import CanadaPostMapperPartial as CanadaPostRateMapperPartial
from .track import CanadaPostMapperPartial as CanadaPostTrackMapperPartial
from .shipment import CanadaPostMapperPartial as CanadaPostShipmentMapperPartial
